// reinhardt-migration-source: 1
use reinhardt::db::migrations::{FieldType, prelude::*};

pub(super) fn migration() -> Migration {
	Migration::new("0009_native_memory", "knowledge")
		.add_dependency("knowledge", "0008_postgres_vectors")
		.add_dependency("registry", "0008_memory_roles")
		.add_operation(Operation::CreateTable { name: "memory_participants".to_owned(), columns: vec![ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true).with_primary_key(true), ColumnDefinition::new("home", FieldType::Text).with_not_null(true), ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true), ColumnDefinition::new("workspace_id", FieldType::Uuid).with_not_null(true),
			ColumnDefinition::new("principal", FieldType::Text).with_not_null(true), ColumnDefinition::new("agent_id", FieldType::Text).with_not_null(true), ColumnDefinition::new("agent_version", FieldType::Text).with_not_null(true), ColumnDefinition::new("revision", FieldType::BigInteger).with_not_null(true), ColumnDefinition::new("deleted", FieldType::Boolean).with_not_null(true)], constraints: vec![
			Constraint::Check { name: "memory_participant_revision".to_owned(), expression: "revision > 0".to_owned() }, Constraint::ForeignKey { name: "memory_participant_workspace".to_owned(), columns: vec!["workspace_id".to_owned()], referenced_table: "workspaces".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		.add_operation(Operation::CreateTable { name: "memory_banks".to_owned(), columns: vec![ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true).with_primary_key(true), ColumnDefinition::new("home", FieldType::Text).with_not_null(true), ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true), ColumnDefinition::new("workspace_id", FieldType::Uuid).with_not_null(true),
			ColumnDefinition::new("participant_id", FieldType::Uuid), ColumnDefinition::new("revision", FieldType::BigInteger).with_not_null(true)], constraints: vec![
			Constraint::ForeignKey { name: "memory_bank_workspace".to_owned(), columns: vec!["workspace_id".to_owned()], referenced_table: "workspaces".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
			Constraint::ForeignKey { name: "memory_bank_participant".to_owned(), columns: vec!["participant_id".to_owned()], referenced_table: "memory_participants".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
			Constraint::Check { name: "memory_bank_revision".to_owned(), expression: "revision > 0 AND revision < 9223372036854775807".to_owned() },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		.add_operation(Operation::CreateTable { name: "memory_units".to_owned(), columns: vec![ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true).with_primary_key(true), ColumnDefinition::new("bank_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("revision", FieldType::BigInteger).with_not_null(true), ColumnDefinition::new("text", FieldType::Text).with_not_null(true), ColumnDefinition::new("kind", FieldType::Text).with_not_null(true), ColumnDefinition::new("learning", FieldType::Text).with_not_null(true), ColumnDefinition::new("verification", FieldType::Text).with_not_null(true),
			ColumnDefinition::new("occurred_start", FieldType::TimestampTz), ColumnDefinition::new("occurred_end", FieldType::TimestampTz),
			ColumnDefinition::new("entities", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("evidence", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("links", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("learned_at", FieldType::TimestampTz).with_not_null(true), ColumnDefinition::new("updated_at", FieldType::TimestampTz).with_not_null(true), ColumnDefinition::new("deleted", FieldType::Boolean).with_not_null(true), ColumnDefinition::new("stale", FieldType::Boolean).with_not_null(true)], constraints: vec![
			Constraint::ForeignKey { name: "memory_unit_bank".to_owned(), columns: vec!["bank_id".to_owned()], referenced_table: "memory_banks".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
			Constraint::Check { name: "memory_unit_revision".to_owned(), expression: "revision > 0 AND revision < 9223372036854775807".to_owned() },
			Constraint::Check { name: "memory_unit_kind".to_owned(), expression: "kind IN ('world','experience','observation','mental_model')".to_owned() },
			Constraint::Check { name: "memory_unit_learning".to_owned(), expression: "learning IN ('fact','preference','procedure','failure')".to_owned() },
			Constraint::Check { name: "memory_unit_verification".to_owned(), expression: "verification IN ('unverified','supported','contradicted')".to_owned() },
			Constraint::Check { name: "memory_unit_occurrence".to_owned(), expression: "(occurred_start IS NULL AND occurred_end IS NULL) OR (occurred_start IS NOT NULL AND occurred_end IS NOT NULL AND occurred_start <= occurred_end)".to_owned() },
			Constraint::Check { name: "memory_unit_provenance".to_owned(), expression: "jsonb_typeof(entities) = 'array' AND jsonb_typeof(evidence) = 'array' AND jsonb_typeof(links) = 'array' AND (kind NOT IN ('observation','mental_model') OR (verification = 'unverified' AND jsonb_array_length(evidence) > 0))".to_owned() },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		.add_operation(Operation::CreateTable { name: "memory_history".to_owned(), columns: vec![ColumnDefinition::new("unit_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("bank_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("revision", FieldType::BigInteger).with_not_null(true), ColumnDefinition::new("operation_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("actor", FieldType::Text).with_not_null(true),
			ColumnDefinition::new("text", FieldType::Text).with_not_null(true), ColumnDefinition::new("kind", FieldType::Text).with_not_null(true), ColumnDefinition::new("learning", FieldType::Text).with_not_null(true), ColumnDefinition::new("verification", FieldType::Text).with_not_null(true),
			ColumnDefinition::new("occurred_start", FieldType::TimestampTz), ColumnDefinition::new("occurred_end", FieldType::TimestampTz),
			ColumnDefinition::new("entities", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("evidence", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("links", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("learned_at", FieldType::TimestampTz).with_not_null(true), ColumnDefinition::new("updated_at", FieldType::TimestampTz).with_not_null(true), ColumnDefinition::new("deleted", FieldType::Boolean).with_not_null(true), ColumnDefinition::new("stale", FieldType::Boolean).with_not_null(true)], constraints: vec![
			Constraint::PrimaryKey { name: "memory_history_pk".into(), columns: vec!["unit_id".into(), "revision".into()] },
			Constraint::ForeignKey { name: "memory_history_bank".to_owned(), columns: vec!["bank_id".to_owned()], referenced_table: "memory_banks".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		.add_operation(Operation::CreateTable { name: "memory_receipts".to_owned(), columns: vec![ColumnDefinition::new("operation_id", FieldType::Uuid).with_not_null(true).with_primary_key(true), ColumnDefinition::new("bank_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("digest", FieldType::Text).with_not_null(true), ColumnDefinition::new("outcome", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("created_at", FieldType::TimestampTz).with_not_null(true)], constraints: vec![
			Constraint::ForeignKey { name: "memory_receipt_bank".to_owned(), columns: vec!["bank_id".to_owned()], referenced_table: "memory_banks".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		.add_operation(Operation::CreateTable { name: "memory_dependencies".to_owned(), columns: vec![ColumnDefinition::new("unit_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("bank_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("source_kind", FieldType::Text).with_not_null(true), ColumnDefinition::new("source_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("source_revision", FieldType::BigInteger).with_not_null(true)], constraints: vec![
			Constraint::PrimaryKey { name: "memory_dependencies_pk".into(), columns: vec!["unit_id".into(), "source_kind".into(), "source_id".into(), "source_revision".into()] },
			Constraint::ForeignKey { name: "memory_dependency_unit".to_owned(), columns: vec!["unit_id".to_owned()], referenced_table: "memory_units".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
			Constraint::ForeignKey { name: "memory_dependency_bank".to_owned(), columns: vec!["bank_id".to_owned()], referenced_table: "memory_banks".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
			Constraint::Check { name: "memory_dependency_kind".to_owned(), expression: "source_kind IN ('unit','message','artifact','run') AND source_revision > 0".to_owned() },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		.add_operation(Operation::CreateTable { name: "memory_candidates".to_owned(), columns: vec![ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true).with_primary_key(true), ColumnDefinition::new("bank_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("revision", FieldType::BigInteger).with_not_null(true), ColumnDefinition::new("run", FieldType::Jsonb).with_not_null(true),
			ColumnDefinition::new("text", FieldType::Text).with_not_null(true), ColumnDefinition::new("kind", FieldType::Text).with_not_null(true), ColumnDefinition::new("learning", FieldType::Text).with_not_null(true), ColumnDefinition::new("verification", FieldType::Text).with_not_null(true),
			ColumnDefinition::new("occurred_start", FieldType::TimestampTz), ColumnDefinition::new("occurred_end", FieldType::TimestampTz),
			ColumnDefinition::new("entities", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("evidence", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("links", FieldType::Jsonb).with_not_null(true), ColumnDefinition::new("state", FieldType::Text).with_not_null(true), ColumnDefinition::new("created_at", FieldType::TimestampTz).with_not_null(true), ColumnDefinition::new("updated_at", FieldType::TimestampTz).with_not_null(true)], constraints: vec![
			Constraint::ForeignKey { name: "memory_candidate_bank".to_owned(), columns: vec!["bank_id".to_owned()], referenced_table: "memory_banks".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
			Constraint::Check { name: "memory_candidate_kind".to_owned(), expression: "kind IN ('world','experience') AND verification = 'unverified' AND revision > 0".to_owned() },
			Constraint::Check { name: "memory_candidate_state".to_owned(), expression: "state IN ('pending','admitted','rejected','invalidated')".to_owned() },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		.add_operation(Operation::CreateTable { name: "memory_run_bindings".to_owned(), columns: vec![ColumnDefinition::new("run_id", FieldType::Uuid).with_not_null(true).with_primary_key(true), ColumnDefinition::new("participant_id", FieldType::Uuid).with_not_null(true), ColumnDefinition::new("provider_id", FieldType::Text).with_not_null(true), ColumnDefinition::new("provider_version", FieldType::Text).with_not_null(true), ColumnDefinition::new("participant_revision", FieldType::BigInteger).with_not_null(true)], constraints: vec![
			Constraint::ForeignKey { name: "memory_binding_run".to_owned(), columns: vec!["run_id".to_owned()], referenced_table: "runs".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None }, Constraint::ForeignKey { name: "memory_binding_participant".to_owned(), columns: vec!["participant_id".to_owned()], referenced_table: "memory_participants".to_owned(), referenced_columns: vec!["id".to_owned()], on_delete: ForeignKeyAction::NoAction, on_update: ForeignKeyAction::NoAction, deferrable: None },
		], without_rowid: None, interleave_in_parent: None, partition: None })
		// Reinhardt cannot express an extension index access method or NULLS NOT DISTINCT.
		.add_operation(Operation::RunSQL { sql: include_str!("sql/forward/0009_native_memory.sql").into(),
			reverse_sql: Some(include_str!("sql/backward/0009_native_memory.sql").into()) })
		.atomic(true)
}
