[package]
name = "migration"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sea-orm-migration = { version = "1.1.19", default-features = false, features = [
  "cli",
  "sqlx-postgres",
  "runtime-tokio-rustls",
] }
