//! Application endpoint registration and access policies.
use super::views::{audit, drafts, incident, profile, test, trust};
use crate::apps::identity::services::boundary::AccessBoundary;
use reinhardt::UnifiedRouter;

pub fn url_patterns() -> UnifiedRouter {
	UnifiedRouter::new().server(|server| {
		server
			.endpoint(drafts::create)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::list)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::get)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::save)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::duplicate)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::adopt)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::share)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::shares)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::transfer)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::archive)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::validate)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::versions)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(drafts::register)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(test::get_limits)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(test::set_limits)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(test::sessions)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(test::stop)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(test::start)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(profile::list)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(profile::put)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(incident::create)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(incident::list)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(incident::get)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(incident::update)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(incident::events)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(audit::audit)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(trust::inspect)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(trust::permission_context)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(trust::report)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
	})
}
