import { Button } from "../components/ui/button";
import { useEffect, useState } from "react";
import { Alert } from "../components/patterns";
import { useI18n } from "../ui";
import { download, saveFile, type CoreFile } from "./client";

/**
 * Capability panel (details or section): hairline-separated rhythm, the
 * panel's own summary row, headings and item articles.
 */
export const panelClass = [
  "grid min-w-0 gap-3 border-t border-border py-3 text-[13px] text-foreground",
  "[&_h2]:text-[13px] [&_h2]:font-semibold [&_h3]:text-[13px] [&_h3]:font-semibold",
  "[&_article]:grid [&_article]:gap-2 [&_article]:border-t [&_article]:border-border [&_article]:py-3",
  "[&>summary]:flex [&>summary]:min-h-8 [&>summary]:cursor-pointer [&>summary]:items-center [&>summary]:gap-2 [&>summary]:text-[13px] [&>summary]:font-semibold [&>summary]:marker:text-muted-foreground [&>summary]:hover:text-brand",
].join(" ");

export function DisplayFile({ area, file }: { area: string; file: CoreFile }) {
  const { locale } = useI18n();
  const ja = locale === "ja-JP";
  const [preview, setPreview] = useState<string>();
  const [error, setError] = useState("");
  const path = `/working-areas/${area}/files/${file.file_id}/download`;
  useEffect(
    () => () => {
      if (preview) URL.revokeObjectURL(preview);
    },
    [preview],
  );
  return (
    <figure className="my-4 grid gap-2 [&_img]:block [&_img]:h-auto [&_img]:max-w-full">
      <figcaption>
        {file.path} · {file.size.toLocaleString()} bytes
      </figcaption>
      {preview && (
        <img
          src={preview}
          alt={ja ? "Python が生成したグラフ" : "Graph generated by Python"}
        />
      )}
      {!preview && file.media_type === "image/png" && (
        <Button
          variant="outline"
          type="button"
          onClick={async () => {
            try {
              const result = await download(path);
              if (result.file.digest !== file.digest)
                throw new Error("Display file changed");
              setPreview(URL.createObjectURL(result.blob));
            } catch (e) {
              setError(String(e));
            }
          }}
        >
          {ja ? "画像を表示" : "Show image"}
        </Button>
      )}
      <Button
        variant="outline"
        type="button"
        onClick={async () => {
          try {
            await saveFile(path);
          } catch (e) {
            setError(String(e));
          }
        }}
      >
        {ja ? "出力をダウンロード" : "Download output"}
      </Button>
      {error && <Alert>{error}</Alert>}
    </figure>
  );
}
