import { useEffect, useState } from "react";
import { useI18n } from "../ui";
import { download, saveFile, type CoreFile } from "./client";

export function DisplayFile({ area, file }: { area: string; file: CoreFile }) {
  const { locale } = useI18n();
  const ja = locale === "ja-JP";
  const [preview, setPreview] = useState<string>();
  const [error, setError] = useState("");
  const path = `/working-areas/${area}/files/${file.file_id}`;
  useEffect(
    () => () => {
      if (preview) URL.revokeObjectURL(preview);
    },
    [preview],
  );
  return (
    <figure className="core-display">
      <figcaption>
        {file.path} · {file.size.toLocaleString()} bytes
      </figcaption>
      {preview && (
        <img
          src={preview}
          alt={ja ? "Python が生成したグラフ" : "Graph generated by Python"}
        />
      )}
      {!preview && file.media_type === "image/png" && (
        <button
          type="button"
          onClick={async () => {
            try {
              const result = await download(path);
              if (result.file.digest !== file.digest)
                throw new Error("Display file changed");
              setPreview(URL.createObjectURL(result.blob));
            } catch (e) {
              setError(String(e));
            }
          }}
        >
          {ja ? "画像を表示" : "Show image"}
        </button>
      )}
      <button
        type="button"
        onClick={async () => {
          try {
            await saveFile(path);
          } catch (e) {
            setError(String(e));
          }
        }}
      >
        {ja ? "出力をダウンロード" : "Download output"}
      </button>
      {error && <p role="alert">{error}</p>}
    </figure>
  );
}
