// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0007_model_state", "execution")
        .add_operation(Operation::CreateTable {
            name: "activation_quarantine".to_string(),
            columns: vec![
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("digest",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(true).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("reason", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("stream_sequence", FieldType::BigInteger)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_areas".to_string(),
            columns: vec![
                ColumnDefinition::new("agent_id", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("constraints", FieldType::Jsonb)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("epoch",
                FieldType::BigInteger).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("generation", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("home_node",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("manifest", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("next_sequence", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("owner",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("state",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("thread_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("workspace_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_objects".to_string(),
            columns: vec![
                ColumnDefinition::new("area_id", FieldType::Uuid).with_not_null(false)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("digest",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("kind", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("size", FieldType::BigInteger).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_operations".to_string(),
            columns: vec![
                ColumnDefinition::new("area_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("credential_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("digest", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("epoch", FieldType::BigInteger).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("generation", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(true)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("input",
                FieldType::Jsonb).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("kind", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("policy_revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("principal",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("request_key", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("result", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("run_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("runner_instance", FieldType::Text)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("state",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("subjects", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("updated_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_quotas".to_string(),
            columns: vec![
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("used_bytes", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_records".to_string(),
            columns: vec![
                ColumnDefinition::new("area_id", FieldType::Uuid).with_not_null(false)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("data", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("expires_at", FieldType::TimestampTz)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(true)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("kind", FieldType::Text)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("owner",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("state",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_requests".to_string(),
            columns: vec![
                ColumnDefinition::new("digest", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("key", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("principal", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("result", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_runs".to_string(),
            columns: vec![
                ColumnDefinition::new("area_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("generation", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("initialized",
                FieldType::Boolean).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("run_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("sequence", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "core_task_sessions".to_string(),
            columns: vec![
                ColumnDefinition::new("task_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("thread_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "events".to_string(),
            columns: vec![
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("data",
                FieldType::Jsonb).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("kind", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("next_attempt_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("node_id",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("publish_error", FieldType::Text)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("published_at",
                FieldType::TimestampTz).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("sequence", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(true)
                .with_auto_increment(true).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("workspace_id",
                FieldType::Uuid).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_budgets".to_string(),
            columns: vec![
                ColumnDefinition::new("compaction_call_limit", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("compaction_calls", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("embedding_call_limit", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("embedding_calls", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("request_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("token_limit", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("used_tokens",
                FieldType::BigInteger).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(Some("0"
                .to_string())).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_compaction_usage".to_string(),
            columns: vec![
                ColumnDefinition::new("attempt_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("provider_id",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("provider_version", FieldType::Text)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("questions",
                FieldType::Integer).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("request_bytes", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("request_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(true).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("run_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_embedding_usage".to_string(),
            columns: vec![
                ColumnDefinition::new("attempt_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("entry_id",
                FieldType::Uuid).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("provider_id", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("provider_version", FieldType::Text)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("purpose",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(Some(FieldDomain::Enum { repr :
                ModelEnumRepr::String, values : vec![ModelEnumValue::String("index"
                .to_string()), ModelEnumValue::String("query".to_string())], })),
                ColumnDefinition::new("reported_tokens", FieldType::BigInteger)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("request_bytes",
                FieldType::BigInteger).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("request_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("reserved_tokens", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("run_id",
                FieldType::Uuid).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("workspace_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![
                Constraint::EnumDomain { name :
                "generation_embedding_usage_purpose_model_enum_check".to_string(), column
                : "purpose".to_string(), domain : FieldDomain::Enum { repr :
                ModelEnumRepr::String, values : vec![ModelEnumValue::String("index"
                .to_string()), ModelEnumValue::String("query".to_string())], }, }
            ],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_history".to_string(),
            columns: vec![
                ColumnDefinition::new("actor", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("reason",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("request_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("sequence", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(true)
                .with_auto_increment(true).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("status",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_policies".to_string(),
            columns: vec![
                ColumnDefinition::new("allocated_compaction_calls",
                FieldType::BigInteger).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(Some("0"
                .to_string())).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("allocated_embedding_calls", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("allocated_tokens", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("generated_count", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("spec",
                FieldType::Jsonb).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_policy_history".to_string(),
            columns: vec![
                ColumnDefinition::new("actor", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("policy_id",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(true).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(true)
                .with_auto_increment(true).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("spec",
                FieldType::Jsonb).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_remote_dispatches".to_string(),
            columns: vec![
                ColumnDefinition::new("attempt_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("boundary", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("digest",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("finalization", FieldType::Jsonb)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("peer_finalized",
                FieldType::Boolean).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("peer_node", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("reservations", FieldType::Jsonb)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("state",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("usage", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_remote_finalizations".to_string(),
            columns: vec![
                ColumnDefinition::new("attempt_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("digest", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("result", FieldType::Jsonb).with_not_null(false)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_remote_intents".to_string(),
            columns: vec![
                ColumnDefinition::new("binding", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("cancel_delivered", FieldType::Boolean)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("cancel_retry_at",
                FieldType::TimestampTz).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("cancelled", FieldType::Boolean)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("created_at",
                FieldType::TimestampTz).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("credential_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(true)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("root_subject",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("subject_chain",
                FieldType::Array(Box::new(FieldType::Text))).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("task_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_remote_usage".to_string(),
            columns: vec![
                ColumnDefinition::new("admission_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("attempt_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(true).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("digest",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("dispatcher_node", FieldType::Text)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("grant_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("operation_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("purpose",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("reported_tokens", FieldType::BigInteger)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("request_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(true).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("reserved_tokens", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("state",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_requests".to_string(),
            columns: vec![
                ColumnDefinition::new("admission_id", FieldType::Uuid)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("agent_id",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("agent_version", FieldType::Text)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("created_at",
                FieldType::TimestampTz).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("credential_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("definition",
                FieldType::Jsonb).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("depth", FieldType::Integer).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("expires_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("foreign_intent",
                FieldType::Jsonb).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("grant_id", FieldType::Uuid).with_not_null(false)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("home_node", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("policy_id", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("policy_revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("prepared",
                FieldType::Boolean).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false)
                .with_default(Some("false".to_string())).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("quota_released",
                FieldType::Boolean).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false)
                .with_default(Some("false".to_string())).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("reason",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("retired_catalog_revision", FieldType::BigInteger)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("root_subject",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("status", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None)
                .with_domain_option(Some(FieldDomain::Enum { repr :
                ModelEnumRepr::String, values : vec![ModelEnumValue::String("ACTIVE"
                .to_string()), ModelEnumValue::String("COMPLETED".to_string()),
                ModelEnumValue::String("DELETED".to_string()),
                ModelEnumValue::String("DENIED".to_string()),
                ModelEnumValue::String("EXPIRED".to_string()),
                ModelEnumValue::String("FAILED".to_string()),
                ModelEnumValue::String("PENDING_APPROVAL".to_string()),
                ModelEnumValue::String("QUEUED".to_string()),
                ModelEnumValue::String("STOPPED".to_string())], })),
                ColumnDefinition::new("subject_chain",
                FieldType::Array(Box::new(FieldType::Text))).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("task_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("local_task_id", FieldType::Uuid)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None)
                .with_generated(Some(GeneratedColumnDefinition::raw_sql("\nCASE\n    WHEN (home_node = ''::text) THEN task_id\n    ELSE NULL::uuid\nEND",
                GeneratedStorage::Stored))).with_domain_option(None),
                ColumnDefinition::new("tenant", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("token_limit", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("workspace_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("local_workspace_id", FieldType::Uuid)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None)
                .with_generated(Some(GeneratedColumnDefinition::raw_sql("\nCASE\n    WHEN (home_node = ''::text) THEN workspace_id\n    ELSE NULL::uuid\nEND",
                GeneratedStorage::Stored))).with_domain_option(None)
            ],
            constraints: vec![
                Constraint::EnumDomain { name :
                "generation_requests_status_model_enum_check".to_string(), column :
                "status".to_string(), domain : FieldDomain::Enum { repr :
                ModelEnumRepr::String, values : vec![ModelEnumValue::String("ACTIVE"
                .to_string()), ModelEnumValue::String("COMPLETED".to_string()),
                ModelEnumValue::String("DELETED".to_string()),
                ModelEnumValue::String("DENIED".to_string()),
                ModelEnumValue::String("EXPIRED".to_string()),
                ModelEnumValue::String("FAILED".to_string()),
                ModelEnumValue::String("PENDING_APPROVAL".to_string()),
                ModelEnumValue::String("QUEUED".to_string()),
                ModelEnumValue::String("STOPPED".to_string())], }, }
            ],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "generation_usage".to_string(),
            columns: vec![
                ColumnDefinition::new("attempt_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("reported_tokens",
                FieldType::BigInteger).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("request_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("reserved_tokens", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("run_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "human_requests".to_string(),
            columns: vec![
                ColumnDefinition::new("answered_by", FieldType::Text)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("created_at",
                FieldType::TimestampTz).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("kind", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None)
                .with_domain_option(Some(FieldDomain::Enum { repr :
                ModelEnumRepr::String, values :
                vec![ModelEnumValue::String("APPROVAL_REQUIRED".to_string()),
                ModelEnumValue::String("CONFIRMATION".to_string()),
                ModelEnumValue::String("INFORMATION_REQUEST".to_string()),
                ModelEnumValue::String("QUESTION".to_string())], })),
                ColumnDefinition::new("prompt", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("request_key", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("response", FieldType::Jsonb).with_not_null(false)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("run_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("workspace_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![
                Constraint::EnumDomain { name : "human_requests_kind_model_enum_check"
                .to_string(), column : "kind".to_string(), domain : FieldDomain::Enum {
                repr : ModelEnumRepr::String, values :
                vec![ModelEnumValue::String("APPROVAL_REQUIRED".to_string()),
                ModelEnumValue::String("CONFIRMATION".to_string()),
                ModelEnumValue::String("INFORMATION_REQUEST".to_string()),
                ModelEnumValue::String("QUESTION".to_string())], }, }
            ],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "inbox".to_string(),
            columns: vec![
                ColumnDefinition::new("event_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("received_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "invocations".to_string(),
            columns: vec![
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("idempotency_key",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(true).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("input", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("replay_safe", FieldType::Boolean)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("result",
                FieldType::Jsonb).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("run_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("status", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None)
                .with_domain_option(Some(FieldDomain::Enum { repr :
                ModelEnumRepr::String, values : vec![ModelEnumValue::String("COMPLETED"
                .to_string()), ModelEnumValue::String("STARTED".to_string()),
                ModelEnumValue::String("UNCERTAIN".to_string())], })),
                ColumnDefinition::new("tool", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![
                Constraint::EnumDomain { name : "invocations_status_model_enum_check"
                .to_string(), column : "status".to_string(), domain : FieldDomain::Enum {
                repr : ModelEnumRepr::String, values :
                vec![ModelEnumValue::String("COMPLETED".to_string()),
                ModelEnumValue::String("STARTED".to_string()),
                ModelEnumValue::String("UNCERTAIN".to_string())], }, }
            ],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "memory".to_string(),
            columns: vec![
                ColumnDefinition::new("agent_id", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("agent_version", FieldType::Text)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("data",
                FieldType::Jsonb).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("home_node", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("workspace_id", FieldType::Uuid)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![Constraint::PrimaryKey { name: "memory_pkey".into(), columns: vec!["agent_id".into(), "agent_version".into(), "workspace_id".into(), "home_node".into()] }],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "run_activations".to_string(),
            columns: vec![
                ColumnDefinition::new("claim_source", FieldType::Text)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("claimed_at",
                FieldType::TimestampTz).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("created_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("disposition",
                FieldType::Text).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("due_at", FieldType::TimestampTz)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("generation",
                FieldType::BigInteger).with_not_null(true).with_unique(false)
                .with_primary_key(true).with_auto_increment(true).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("lease_token", FieldType::Uuid)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("publication_epoch",
                FieldType::BigInteger).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("publish_token", FieldType::Uuid)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("publish_until",
                FieldType::TimestampTz).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("published_at", FieldType::TimestampTz)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("reason",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("run_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("run_revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("state",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("worker_pid", FieldType::BigInteger)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "run_inputs".to_string(),
            columns: vec![
                ColumnDefinition::new("content", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("delivery_retry_at", FieldType::TimestampTz)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("idempotency_key",
                FieldType::Text).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("message_id", FieldType::Uuid).with_not_null(false)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("reference_only", FieldType::Boolean)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("false".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("run_id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("sender", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("seq", FieldType::BigInteger).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(true)
                .with_default(None).with_generated(None).with_domain_option(None)
            ],
            constraints: vec![],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_operation(Operation::CreateTable {
            name: "runs".to_string(),
            columns: vec![
                ColumnDefinition::new("agent_id", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("agent_version", FieldType::Text)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("context",
                FieldType::Jsonb).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("control", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None)
                .with_domain_option(Some(FieldDomain::Enum { repr :
                ModelEnumRepr::String, values : vec![ModelEnumValue::String("ACTIVE"
                .to_string()), ModelEnumValue::String("CANCELLED".to_string()),
                ModelEnumValue::String("PAUSED".to_string())], })),
                ColumnDefinition::new("error", FieldType::Text).with_not_null(false)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("home_node", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("id", FieldType::Uuid).with_not_null(true)
                .with_unique(false).with_primary_key(true).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("lease_owner", FieldType::Uuid)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("lease_until",
                FieldType::TimestampTz).with_not_null(false).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("ledger_worker_ready", FieldType::Boolean)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("false".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("observed_input_seq", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("pending", FieldType::Jsonb).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None).with_domain_option(None),
                ColumnDefinition::new("pending_human_request_id", FieldType::Uuid)
                .with_not_null(false).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None)
                .with_generated(Some(GeneratedColumnDefinition::raw_sql("\nCASE\n    WHEN ((((pending -> 'data'::text) ->> 'reason'::text) = ANY (ARRAY['human'::text, 'external_approval'::text, 'reconciliation'::text])) AND (jsonb_typeof(((pending -> 'data'::text) -> 'request_id'::text)) = 'string'::text) AND (((pending -> 'data'::text) ->> 'request_id'::text) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text)) THEN (((pending -> 'data'::text) ->> 'request_id'::text))::uuid\n    ELSE NULL::uuid\nEND",
                GeneratedStorage::Stored))).with_domain_option(None),
                ColumnDefinition::new("phase", FieldType::Text).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(None).with_generated(None)
                .with_domain_option(Some(FieldDomain::Enum { repr :
                ModelEnumRepr::String, values : vec![ModelEnumValue::String("CANCELLED"
                .to_string()), ModelEnumValue::String("COMPLETED".to_string()),
                ModelEnumValue::String("FAILED".to_string()),
                ModelEnumValue::String("READY".to_string()),
                ModelEnumValue::String("THINKING".to_string()),
                ModelEnumValue::String("TOOL_CALL".to_string()),
                ModelEnumValue::String("WAITING".to_string())], })),
                ColumnDefinition::new("revision", FieldType::BigInteger)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(Some("0".to_string()))
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("step", FieldType::Integer).with_not_null(true)
                .with_unique(false).with_primary_key(false).with_auto_increment(false)
                .with_default(Some("0".to_string())).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("task_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None),
                ColumnDefinition::new("updated_at", FieldType::TimestampTz)
                .with_not_null(true).with_unique(false).with_primary_key(false)
                .with_auto_increment(false).with_default(None).with_generated(None)
                .with_domain_option(None), ColumnDefinition::new("workspace_id",
                FieldType::Uuid).with_not_null(true).with_unique(false)
                .with_primary_key(false).with_auto_increment(false).with_default(None)
                .with_generated(None).with_domain_option(None)
            ],
            constraints: vec![
                Constraint::EnumDomain { name : "runs_phase_model_enum_check"
                .to_string(), column : "phase".to_string(), domain : FieldDomain::Enum {
                repr : ModelEnumRepr::String, values :
                vec![ModelEnumValue::String("CANCELLED".to_string()),
                ModelEnumValue::String("COMPLETED".to_string()),
                ModelEnumValue::String("FAILED".to_string()),
                ModelEnumValue::String("READY".to_string()),
                ModelEnumValue::String("THINKING".to_string()),
                ModelEnumValue::String("TOOL_CALL".to_string()),
                ModelEnumValue::String("WAITING".to_string())], }, },
                Constraint::EnumDomain { name : "runs_control_model_enum_check"
                .to_string(), column : "control".to_string(), domain : FieldDomain::Enum
                { repr : ModelEnumRepr::String, values :
                vec![ModelEnumValue::String("ACTIVE".to_string()),
                ModelEnumValue::String("CANCELLED".to_string()),
                ModelEnumValue::String("PAUSED".to_string())], }, }
            ],
            without_rowid: None,
            interleave_in_parent: None,
            partition: None,
        })
        .add_dependency("workspaces", "0007_model_state")
        .atomic(true)
        .with_initial(None)
        .state_only(true)
        .database_only(false)
}
