// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.
// Align logical ORM metadata; retain the separately enforced physical constraints.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0010_native_memory_model_state", "execution")
		.add_operation(Operation::DropConstraintDefinition {
			table: "generation_remote_usage".to_string(),
			constraint: Constraint::Check {
				name: "generation_remote_usage_purpose_check".to_string(),
				expression: "purpose IN ('embedding', 'inference', 'compaction', 'memory')"
					.to_string(),
			},
		})
		.add_operation(Operation::DropConstraintDefinition {
			table: "run_task_snapshots".to_string(),
			constraint: Constraint::Check {
				name: "run_task_snapshot_bounds".to_string(),
				expression: "task_revision >= 0 AND step >= 0 AND input_seq >= 0".to_string(),
			},
		})
		.add_operation(Operation::DropConstraintDefinition {
			table: "run_task_snapshots".to_string(),
			constraint: Constraint::ForeignKey {
				name: "run_task_snapshot_run".to_string(),
				columns: vec!["run_id".to_string()],
				referenced_table: "runs".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Cascade,
				on_update: ForeignKeyAction::Restrict,
				deferrable: None,
			},
		})
		.add_dependency("execution", "0009_run_task_snapshots")
		.atomic(true)
		.with_initial(None)
		.state_only(true)
		.database_only(false)
}
