// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.
// Align logical ORM metadata; retain the physical lookup index, created_at default
// and the separately enforced references and checks from 0012_inference_usage.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0013_inference_usage_model_state", "execution")
		.add_operation(Operation::DropNamedIndex {
			table: "inference_usage".to_string(),
			name: "idx_inference_usage_run_id_outcome".to_string(),
			columns: vec!["run_id".to_string(), "outcome".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_operation(Operation::AlterColumn {
			table: "inference_usage".to_string(),
			column: "created_at".to_string(),
			old_definition: Some(
				ColumnDefinition::new("created_at", FieldType::TimestampTz)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(Some("now()".to_string()))
					.with_generated(None)
					.with_domain_option(None),
			),
			new_definition: ColumnDefinition::new("created_at", FieldType::TimestampTz)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			mysql_options: None,
		})
		.add_operation(Operation::DropConstraintDefinition {
			table: "inference_usage".to_string(),
			constraint: Constraint::Check {
				name: "inference_usage_counts".to_string(),
				expression: "projection_version > 0 AND estimator_version > 0 AND estimated_tokens >= 0 AND input_tokens >= 0 AND output_tokens >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0 AND reasoning_tokens >= 0 AND cost_nanocredits >= 0 AND upstream_cost_nanocredits >= 0"
					.to_string(),
			},
		})
		.add_operation(Operation::DropConstraintDefinition {
			table: "inference_usage".to_string(),
			constraint: Constraint::Check {
				name: "inference_usage_estimate_confidence".to_string(),
				expression: "estimate_confidence IN ('exact', 'calibrated', 'conservative')"
					.to_string(),
			},
		})
		.add_operation(Operation::DropConstraintDefinition {
			table: "inference_usage".to_string(),
			constraint: Constraint::Check {
				name: "inference_usage_outcome".to_string(),
				expression: "outcome IN ('dispatched', 'completed', 'rejected', 'unknown') AND (outcome = 'dispatched') = (completed_at IS NULL) AND (outcome = 'rejected') = (rejection_class IS NOT NULL)"
					.to_string(),
			},
		})
		.add_operation(Operation::DropConstraintDefinition {
			table: "inference_usage".to_string(),
			constraint: Constraint::Check {
				name: "inference_usage_reported_only_when_completed".to_string(),
				expression: "outcome = 'completed' OR num_nonnulls(input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, cost_nanocredits, upstream_cost_nanocredits) = 0"
					.to_string(),
			},
		})
		.add_operation(Operation::DropConstraintDefinition {
			table: "inference_usage".to_string(),
			constraint: Constraint::ForeignKey {
				name: "inference_usage_run".to_string(),
				columns: vec!["run_id".to_string()],
				referenced_table: "runs".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Cascade,
				on_update: ForeignKeyAction::Restrict,
				deferrable: None,
			},
		})
		.add_dependency("execution", "0012_inference_usage")
		.atomic(true)
		.with_initial(None)
		.state_only(true)
		.database_only(false)
}
