ALTER TABLE tasks DROP CONSTRAINT tasks_status_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_status_check CHECK (status IN ('OPEN','CLAIMED','RUNNING','COMPLETED','FAILED','BLOCKED','CANCELLED','ABANDONED'));
