ALTER TABLE registry DROP CONSTRAINT registry_embedding_config;
ALTER TABLE registry ADD CONSTRAINT registry_embedding_config CHECK (COALESCE((true AND ((kind <> 'embedding'::text) OR (
						CASE
						WHEN (jsonb_typeof((metadata -> 'config'::text)) = 'object'::text) THEN (((metadata -> 'config'::text) - ARRAY['provider'::text, 'endpoint'::text, 'credential_env'::text, 'model'::text, 'model_version'::text, 'dimensions'::text]) = '{}'::jsonb)
						ELSE false
						END AND (jsonb_typeof(((metadata -> 'config'::text) -> 'provider'::text)) = 'string'::text) AND (((metadata -> 'config'::text) ->> 'provider'::text) = 'openai'::text) AND (jsonb_typeof(((metadata -> 'config'::text) -> 'endpoint'::text)) = 'string'::text) AND (((metadata -> 'config'::text) ->> 'endpoint'::text) ~ '^https?://[^/@?#[:space:]]+'::text) AND (jsonb_typeof(COALESCE(((metadata -> 'config'::text) -> 'credential_env'::text), 'null'::jsonb)) = ANY (ARRAY['string'::text, 'null'::text])) AND ((jsonb_typeof(COALESCE(((metadata -> 'config'::text) -> 'credential_env'::text), 'null'::jsonb)) <> 'string'::text) OR (((metadata -> 'config'::text) ->> 'credential_env'::text) ~ '^AIDASH_SECRET_[A-Z0-9_]*$'::text)) AND (jsonb_typeof(((metadata -> 'config'::text) -> 'model'::text)) = 'string'::text) AND (length(btrim(((metadata -> 'config'::text) ->> 'model'::text), E'\u0009\u000a\u000b\u000c\u000d \u0085\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000'::text)) > 0) AND (octet_length(((metadata -> 'config'::text) ->> 'model'::text)) <= 256) AND (jsonb_typeof(((metadata -> 'config'::text) -> 'model_version'::text)) = 'string'::text) AND (length(btrim(((metadata -> 'config'::text) ->> 'model_version'::text), E'\u0009\u000a\u000b\u000c\u000d \u0085\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000'::text)) > 0) AND (octet_length(((metadata -> 'config'::text) ->> 'model_version'::text)) <= 128) AND
						CASE
						WHEN ((jsonb_typeof(((metadata -> 'config'::text) -> 'dimensions'::text)) = 'number'::text) AND ((((metadata -> 'config'::text) -> 'dimensions'::text))::text ~ '^(0|[1-9][0-9]*)$'::text)) THEN ((((((metadata -> 'config'::text) -> 'dimensions'::text))::text)::numeric >= (1)::numeric) AND (((((metadata -> 'config'::text) -> 'dimensions'::text))::text)::numeric <= (8192)::numeric))
						ELSE false
						END))), false));
