SET LOCAL search_path = public, pg_catalog;

CREATE TRIGGER aidash_activation AFTER UPDATE OF status ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.aidash_activation_trigger();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.artifacts FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.channel_attachments FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.channel_message_context FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.channel_threads FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.conversations FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.messages FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.tasks FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.workspaces FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER gate_legacy_federated_run_message BEFORE INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.gate_legacy_federated_run_message();
CREATE TRIGGER gate_legacy_run_message BEFORE INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.gate_legacy_run_message();
CREATE TRIGGER gate_legacy_run_output BEFORE INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.gate_legacy_run_output();
CREATE TRIGGER gate_remote_task_terminal BEFORE UPDATE OF status ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.gate_remote_task_terminal();
CREATE TRIGGER legacy_run_input_bridge AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.legacy_run_input_bridge();
CREATE TRIGGER task_dependencies_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.task_dependencies FOR EACH STATEMENT EXECUTE FUNCTION public.guard_task_dependencies();
CREATE TRIGGER tasks_dependencies_sync AFTER INSERT OR UPDATE OF id, workspace_id, dependencies ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.sync_task_dependencies();
CREATE TRIGGER tasks_hierarchy_serialize BEFORE INSERT OR UPDATE OF id, parent_id, workspace_id, dependencies ON public.tasks FOR EACH STATEMENT EXECUTE FUNCTION public.lock_task_hierarchy_before_change();
CREATE CONSTRAINT TRIGGER tasks_parent_cycle_guard AFTER INSERT OR UPDATE OF id, parent_id, workspace_id ON public.tasks DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.guard_task_parent_cycle();
CREATE CONSTRAINT TRIGGER zz_tasks_dependency_cycle_guard AFTER INSERT OR UPDATE OF id, parent_id, dependencies ON public.tasks DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.guard_task_dependency_cycle();
