use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

fn table(name: &str) -> TableCreateStatement {
	Table::create().table(Alias::new(name)).to_owned()
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.create_table(
				table("dashboard_identities")
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("issuer")).text().not_null())
					.col(ColumnDef::new(Alias::new("subject")).text().not_null())
					.col(ColumnDef::new(Alias::new("last_valid_at")).timestamp_with_time_zone())
					.col(ColumnDef::new(Alias::new("disabled_at")).timestamp_with_time_zone())
					.index(
						Index::create()
							.name("dashboard_identity_key")
							.col(Alias::new("issuer"))
							.col(Alias::new("subject"))
							.unique(),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				table("dashboard_mappings")
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("identity_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("tenant")).text().not_null())
					.col(ColumnDef::new(Alias::new("subject")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("credential_id"))
							.uuid()
							.not_null()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("enabled"))
							.boolean()
							.not_null()
							.default(true),
					)
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(1),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_mappings"))
							.from_col(Alias::new("identity_id"))
							.to_tbl(Alias::new("dashboard_identities"))
							.to_col(Alias::new("id")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_mappings"))
							.from_col(Alias::new("credential_id"))
							.to_tbl(Alias::new("authorization_credentials"))
							.to_col(Alias::new("id")),
					)
					.index(
						Index::create()
							.name("dashboard_mapping_key")
							.col(Alias::new("identity_id"))
							.col(Alias::new("tenant"))
							.col(Alias::new("subject"))
							.unique(),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				table("dashboard_operator_grants")
					.col(
						ColumnDef::new(Alias::new("identity_id"))
							.uuid()
							.primary_key(),
					)
					.col(
						ColumnDef::new(Alias::new("enabled"))
							.boolean()
							.not_null()
							.default(true),
					)
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(1),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_operator_grants"))
							.from_col(Alias::new("identity_id"))
							.to_tbl(Alias::new("dashboard_identities"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				table("dashboard_login_transactions")
					.col(
						ColumnDef::new(Alias::new("state_hash"))
							.binary()
							.primary_key(),
					)
					.col(
						ColumnDef::new(Alias::new("browser_hash"))
							.binary()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("nonce")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("pkce_verifier"))
							.text()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("return_to")).text().not_null())
					.col(ColumnDef::new(Alias::new("callback_uri")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("expires_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				table("dashboard_sessions")
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(
						ColumnDef::new(Alias::new("token_hash"))
							.binary()
							.not_null()
							.unique_key(),
					)
					.col(ColumnDef::new(Alias::new("csrf_hash")).binary().not_null())
					.col(ColumnDef::new(Alias::new("identity_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("provider_sid")).text())
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("last_activity_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("expires_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("revoked_at")).timestamp_with_time_zone())
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_sessions"))
							.from_col(Alias::new("identity_id"))
							.to_tbl(Alias::new("dashboard_identities"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				table("dashboard_logout_tokens")
					.col(
						ColumnDef::new(Alias::new("jti_hash"))
							.binary()
							.primary_key(),
					)
					.col(
						ColumnDef::new(Alias::new("expires_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				table("dashboard_registration_requests")
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("identity_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("status")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("expires_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("decided_at")).timestamp_with_time_zone())
					.col(ColumnDef::new(Alias::new("decided_by")).uuid())
					.col(ColumnDef::new(Alias::new("decision_actor")).text())
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_registration_requests"))
							.from_col(Alias::new("identity_id"))
							.to_tbl(Alias::new("dashboard_identities"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				table("dashboard_execution_origins")
					.col(ColumnDef::new(Alias::new("run_id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("identity_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("mapping_id")).uuid().not_null())
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_execution_origins"))
							.from_col(Alias::new("run_id"))
							.to_tbl(Alias::new("runs"))
							.to_col(Alias::new("id")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_execution_origins"))
							.from_col(Alias::new("identity_id"))
							.to_tbl(Alias::new("dashboard_identities"))
							.to_col(Alias::new("id")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("dashboard_execution_origins"))
							.from_col(Alias::new("mapping_id"))
							.to_tbl(Alias::new("dashboard_mappings"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		Ok(())
	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		for name in [
			"dashboard_execution_origins",
			"dashboard_registration_requests",
			"dashboard_sessions",
			"dashboard_logout_tokens",
			"dashboard_login_transactions",
			"dashboard_operator_grants",
			"dashboard_mappings",
			"dashboard_identities",
		] {
			manager
				.drop_table(Table::drop().table(Alias::new(name)).to_owned())
				.await?;
		}
		Ok(())
	}
}
