use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.create_table(
				Table::create()
					.table(Alias::new("registry"))
					.col(ColumnDef::new(Alias::new("id")).text().not_null())
					.col(ColumnDef::new(Alias::new("version")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("kind"))
							.text()
							.not_null()
							.check(Expr::cust(
								"kind IN ('agent','model','tool','skill','cluster','node')",
							)),
					)
					.col(
						ColumnDef::new(Alias::new("metadata"))
							.json_binary()
							.not_null(),
					)
					.primary_key(
						Index::create()
							.col(Alias::new("id"))
							.col(Alias::new("version")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("registry_metadata")
					.table(Alias::new("registry"))
					.col(Alias::new("metadata"))
					.index_type(IndexType::Custom(Alias::new("gin").into_iden()))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("workspaces"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("title")).text().not_null())
					.col(ColumnDef::new(Alias::new("goal")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("state"))
							.json_binary()
							.not_null()
							.default(Expr::cust("'{}'")),
					)
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(Expr::cust("0")),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("tasks"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("title")).text().not_null())
					.col(ColumnDef::new(Alias::new("description")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("status"))
							.text()
							.not_null()
							.default(Expr::cust("'OPEN'"))
							.check(Expr::cust(
								"status IN ('OPEN','CLAIMED','RUNNING','COMPLETED','FAILED','BLOCKED','CANCELLED')",
							)),
					)
					.col(
						ColumnDef::new(Alias::new("requirements"))
							.json_binary()
							.not_null()
							.default(Expr::cust("'{}'")),
					)
					.col(ColumnDef::new(Alias::new("owner")).text())
					.col(ColumnDef::new(Alias::new("created_by")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("dependencies"))
							.array(ColumnType::Uuid)
							.not_null()
							.default(Expr::cust("'{}'")),
					)
					.col(ColumnDef::new(Alias::new("parent_id")).uuid())
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(Expr::cust("0")),
					)
					.col(
						ColumnDef::new(Alias::new("creation_key"))
							.text()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("completion_key"))
							.text()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.check(Expr::cust(
						"(status = 'OPEN' AND owner IS NULL) OR status <> 'OPEN'",
					))
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("tasks"))
							.from_col(Alias::new("workspace_id"))
							.to_tbl(Alias::new("workspaces"))
							.to_col(Alias::new("id")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("tasks"))
							.from_col(Alias::new("parent_id"))
							.to_tbl(Alias::new("tasks"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("tasks_workspace")
					.table(Alias::new("tasks"))
					.col(Alias::new("workspace_id"))
					.col(Alias::new("created_at"))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("events"))
					.col(
						ColumnDef::new(Alias::new("sequence"))
							.big_integer()
							.primary_key()
							.extra("GENERATED ALWAYS AS IDENTITY".to_owned()),
					)
					.col(
						ColumnDef::new(Alias::new("id"))
							.uuid()
							.not_null()
							.unique_key(),
					)
					.col(ColumnDef::new(Alias::new("node_id")).text().not_null())
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid())
					.col(ColumnDef::new(Alias::new("kind")).text().not_null())
					.col(ColumnDef::new(Alias::new("data")).json_binary().not_null())
					.col(ColumnDef::new(Alias::new("published_at")).timestamp_with_time_zone())
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("events"))
							.from_col(Alias::new("workspace_id"))
							.to_tbl(Alias::new("workspaces"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("events_outbox")
					.table(Alias::new("events"))
					.col(Alias::new("sequence"))
					.and_where(Expr::cust("published_at IS NULL"))
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("events_workspace")
					.table(Alias::new("events"))
					.col(Alias::new("workspace_id"))
					.col(Alias::new("sequence"))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("inbox"))
					.col(ColumnDef::new(Alias::new("event_id")).uuid().primary_key())
					.col(
						ColumnDef::new(Alias::new("received_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("artifacts"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("task_id")).uuid().not_null())
					.col(
						ColumnDef::new(Alias::new("kind"))
							.text()
							.not_null()
							.check(Expr::cust(
								"kind IN ('text','json','file_reference','code','structured_result')",
							)),
					)
					.col(ColumnDef::new(Alias::new("name")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("content"))
							.json_binary()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("created_by")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("idempotency_key"))
							.text()
							.not_null()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("artifacts"))
							.from_col(Alias::new("workspace_id"))
							.to_tbl(Alias::new("workspaces"))
							.to_col(Alias::new("id")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("artifacts"))
							.from_col(Alias::new("task_id"))
							.to_tbl(Alias::new("tasks"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("conversations"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("target")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("target_kind"))
							.text()
							.not_null()
							.check(Expr::cust("target_kind IN ('agent', 'cluster')")),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("conversations"))
							.from_col(Alias::new("workspace_id"))
							.to_tbl(Alias::new("workspaces"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("messages"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("sender")).text().not_null())
					.col(ColumnDef::new(Alias::new("content")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("idempotency_key"))
							.text()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("messages"))
							.from_col(Alias::new("workspace_id"))
							.to_tbl(Alias::new("workspaces"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("runs"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("task_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("home_node")).text().not_null())
					.col(ColumnDef::new(Alias::new("agent_id")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("agent_version"))
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("phase"))
							.text()
							.not_null()
							.default(Expr::cust("'READY'"))
							.check(Expr::cust(
								"phase IN ('READY','THINKING','TOOL_CALL','WAITING','COMPLETED','FAILED','CANCELLED')",
							)),
					)
					.col(
						ColumnDef::new(Alias::new("control"))
							.text()
							.not_null()
							.default(Expr::cust("'ACTIVE'"))
							.check(Expr::cust("control IN ('ACTIVE','PAUSED','CANCELLED')")),
					)
					.col(
						ColumnDef::new(Alias::new("context"))
							.json_binary()
							.not_null()
							.default(Expr::cust("'{}'")),
					)
					.col(
						ColumnDef::new(Alias::new("pending"))
							.json_binary()
							.not_null()
							.default(Expr::cust("'{}'")),
					)
					.col(
						ColumnDef::new(Alias::new("step"))
							.integer()
							.not_null()
							.default(Expr::cust("0")),
					)
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(Expr::cust("0")),
					)
					.col(ColumnDef::new(Alias::new("error")).text())
					.col(ColumnDef::new(Alias::new("lease_owner")).uuid())
					.col(ColumnDef::new(Alias::new("lease_until")).timestamp_with_time_zone())
					.col(
						ColumnDef::new(Alias::new("updated_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.index(
						Index::create()
							.col(Alias::new("home_node"))
							.col(Alias::new("task_id"))
							.unique(),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("runs_ready")
					.table(Alias::new("runs"))
					.col(Alias::new("updated_at"))
					.and_where(Expr::cust(
						"phase NOT IN ('COMPLETED','FAILED','CANCELLED')",
					))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("invocations"))
					.col(
						ColumnDef::new(Alias::new("idempotency_key"))
							.text()
							.primary_key(),
					)
					.col(ColumnDef::new(Alias::new("run_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("tool")).text().not_null())
					.col(ColumnDef::new(Alias::new("input")).json_binary().not_null())
					.col(
						ColumnDef::new(Alias::new("status"))
							.text()
							.not_null()
							.check(Expr::cust("status IN ('STARTED','COMPLETED','UNCERTAIN')")),
					)
					.col(ColumnDef::new(Alias::new("result")).json_binary())
					.col(
						ColumnDef::new(Alias::new("replay_safe"))
							.boolean()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("invocations"))
							.from_col(Alias::new("run_id"))
							.to_tbl(Alias::new("runs"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("human_requests"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("run_id")).uuid().not_null())
					.col(
						ColumnDef::new(Alias::new("kind"))
							.text()
							.not_null()
							.check(Expr::cust(
								"kind IN ('QUESTION','APPROVAL_REQUIRED','CONFIRMATION','INFORMATION_REQUEST')",
							)),
					)
					.col(ColumnDef::new(Alias::new("prompt")).text().not_null())
					.col(ColumnDef::new(Alias::new("response")).json_binary())
					.col(
						ColumnDef::new(Alias::new("request_key"))
							.text()
							.not_null()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("human_requests"))
							.from_col(Alias::new("run_id"))
							.to_tbl(Alias::new("runs"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("memory"))
					.col(ColumnDef::new(Alias::new("agent_id")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("agent_version"))
							.text()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
					.col(
						ColumnDef::new(Alias::new("data"))
							.json_binary()
							.not_null()
							.default(Expr::cust("'{}'")),
					)
					.primary_key(
						Index::create()
							.col(Alias::new("agent_id"))
							.col(Alias::new("agent_version"))
							.col(Alias::new("workspace_id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("peers"))
					.col(ColumnDef::new(Alias::new("node_id")).text().primary_key())
					.col(ColumnDef::new(Alias::new("endpoint")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("credential_env"))
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("protocol_version"))
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("enabled"))
							.boolean()
							.not_null()
							.default(Expr::cust("true")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("packages"))
					.col(ColumnDef::new(Alias::new("id")).text().not_null())
					.col(ColumnDef::new(Alias::new("version")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("manifest"))
							.json_binary()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("digest")).text().not_null())
					.primary_key(
						Index::create()
							.col(Alias::new("id"))
							.col(Alias::new("version")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("installations"))
					.col(ColumnDef::new(Alias::new("id")).text().not_null())
					.col(ColumnDef::new(Alias::new("version")).text().not_null())
					.col(ColumnDef::new(Alias::new("digest")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("config"))
							.json_binary()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("installed_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::cust("now()")),
					)
					.primary_key(
						Index::create()
							.col(Alias::new("id"))
							.col(Alias::new("version")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("installations"))
							.from_col(Alias::new("id"))
							.from_col(Alias::new("version"))
							.to_tbl(Alias::new("registry"))
							.to_col(Alias::new("id"))
							.to_col(Alias::new("version")),
					)
					.to_owned(),
			)
			.await?;
		Ok(())
	}
	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.drop_table(Table::drop().table(Alias::new("installations")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("packages")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("peers")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("memory")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("human_requests")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("invocations")).to_owned())
			.await?;
		manager
			.drop_index(
				Index::drop()
					.name("runs_ready")
					.table(Alias::new("runs"))
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("runs")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("messages")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("conversations")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("artifacts")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("inbox")).to_owned())
			.await?;
		manager
			.drop_index(
				Index::drop()
					.name("events_workspace")
					.table(Alias::new("events"))
					.to_owned(),
			)
			.await?;
		manager
			.drop_index(
				Index::drop()
					.name("events_outbox")
					.table(Alias::new("events"))
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("events")).to_owned())
			.await?;
		manager
			.drop_index(
				Index::drop()
					.name("tasks_workspace")
					.table(Alias::new("tasks"))
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("tasks")).to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("workspaces")).to_owned())
			.await?;
		manager
			.drop_index(
				Index::drop()
					.name("registry_metadata")
					.table(Alias::new("registry"))
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(Table::drop().table(Alias::new("registry")).to_owned())
			.await?;
		Ok(())
	}
}
