use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("generation_policies"))
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(ColumnDef::new(Alias::new("id")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .big_integer()
                            .not_null()
                            .check(Expr::cust("revision > 0")),
                    )
                    .col(ColumnDef::new(Alias::new("spec")).json_binary().not_null())
                    .col(
                        ColumnDef::new(Alias::new("generated_count"))
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0"))
                            .check(Expr::cust("generated_count >= 0")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("allocated_tokens"))
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0"))
                            .check(Expr::cust("allocated_tokens >= 0")),
                    )
                    .primary_key(
                        Index::create()
                            .col(Alias::new("tenant"))
                            .col(Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("generation_policies"))
                            .from_col(Alias::new("tenant"))
                            .to_tbl(Alias::new("authorization_bundles"))
                            .to_col(Alias::new("tenant")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("generation_policy_history"))
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(ColumnDef::new(Alias::new("policy_id")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("spec")).json_binary().not_null())
                    .col(ColumnDef::new(Alias::new("actor")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .primary_key(
                        Index::create()
                            .col(Alias::new("tenant"))
                            .col(Alias::new("policy_id"))
                            .col(Alias::new("revision")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("generation_policy_history"))
                            .from_col(Alias::new("tenant"))
                            .from_col(Alias::new("policy_id"))
                            .to_tbl(Alias::new("generation_policies"))
                            .to_col(Alias::new("tenant"))
                            .to_col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_task_origins"))
                    .col(ColumnDef::new(Alias::new("task_id")).uuid().primary_key())
                    .col(
                        ColumnDef::new(Alias::new("source_run_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(ColumnDef::new(Alias::new("root_subject")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("subject_chain"))
                            .array(ColumnType::Text)
                            .not_null()
                            .check(Expr::cust("cardinality(subject_chain) BETWEEN 2 AND 32")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_task_origins"))
                            .from_col(Alias::new("task_id"))
                            .to_tbl(Alias::new("tasks"))
                            .to_col(Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_task_origins"))
                            .from_col(Alias::new("source_run_id"))
                            .to_tbl(Alias::new("runs"))
                            .to_col(Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_task_origins"))
                            .from_col(Alias::new("tenant"))
                            .to_tbl(Alias::new("authorization_bundles"))
                            .to_col(Alias::new("tenant")),
                    )
                    .to_owned(),
            )
            .await?;
        manager.create_table(Table::create().table(Alias::new("generation_requests")).col(ColumnDef::new(Alias::new("id")).uuid().primary_key()).col(ColumnDef::new(Alias::new("tenant")).text().not_null()).col(ColumnDef::new(Alias::new("policy_id")).text().not_null()).col(ColumnDef::new(Alias::new("policy_revision")).big_integer().not_null()).col(ColumnDef::new(Alias::new("task_id")).uuid().not_null().unique_key()).col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null()).col(ColumnDef::new(Alias::new("credential_id")).uuid().not_null()).col(ColumnDef::new(Alias::new("root_subject")).text().not_null()).col(ColumnDef::new(Alias::new("subject_chain")).array(ColumnType::Text).not_null().check(Expr::cust("cardinality(subject_chain) BETWEEN 1 AND 31"))).col(ColumnDef::new(Alias::new("agent_id")).text().not_null().unique_key()).col(ColumnDef::new(Alias::new("agent_version")).text().not_null()).col(ColumnDef::new(Alias::new("definition")).json_binary().not_null()).col(ColumnDef::new(Alias::new("status")).text().not_null().check(Expr::cust("status IN ('PENDING_APPROVAL','QUEUED','ACTIVE','COMPLETED','DENIED','STOPPED','EXPIRED','FAILED','DELETED')"))).col(ColumnDef::new(Alias::new("reason")).text().not_null()).col(ColumnDef::new(Alias::new("depth")).integer().not_null().check(Expr::cust("depth BETWEEN 1 AND 31"))).col(ColumnDef::new(Alias::new("token_limit")).big_integer().not_null().check(Expr::cust("token_limit > 0"))).col(ColumnDef::new(Alias::new("quota_released")).boolean().not_null().default(Expr::cust("false"))).col(ColumnDef::new(Alias::new("expires_at")).timestamp_with_time_zone().not_null()).col(ColumnDef::new(Alias::new("created_at")).timestamp_with_time_zone().not_null().default(Expr::cust("now()"))).foreign_key(ForeignKey::create().from_tbl(Alias::new("generation_requests")).from_col(Alias::new("task_id")).to_tbl(Alias::new("tasks")).to_col(Alias::new("id"))).foreign_key(ForeignKey::create().from_tbl(Alias::new("generation_requests")).from_col(Alias::new("workspace_id")).to_tbl(Alias::new("authorization_workspaces")).to_col(Alias::new("workspace_id"))).foreign_key(ForeignKey::create().from_tbl(Alias::new("generation_requests")).from_col(Alias::new("credential_id")).to_tbl(Alias::new("authorization_credentials")).to_col(Alias::new("id"))).foreign_key(ForeignKey::create().from_tbl(Alias::new("generation_requests")).from_col(Alias::new("tenant")).from_col(Alias::new("policy_id")).from_col(Alias::new("policy_revision")).to_tbl(Alias::new("generation_policy_history")).to_col(Alias::new("tenant")).to_col(Alias::new("policy_id")).to_col(Alias::new("revision"))).to_owned()).await?;
        manager
            .create_index(
                Index::create()
                    .name("generation_requests_policy")
                    .table(Alias::new("generation_requests"))
                    .col(Alias::new("tenant"))
                    .col(Alias::new("policy_id"))
                    .col(Alias::new("status"))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("generation_history"))
                    .col(
                        ColumnDef::new(Alias::new("sequence"))
                            .big_integer()
                            .primary_key()
                            .extra("GENERATED ALWAYS AS IDENTITY".to_owned()),
                    )
                    .col(ColumnDef::new(Alias::new("request_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("status")).text().not_null())
                    .col(ColumnDef::new(Alias::new("actor")).text().not_null())
                    .col(ColumnDef::new(Alias::new("reason")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("generation_history"))
                            .from_col(Alias::new("request_id"))
                            .to_tbl(Alias::new("generation_requests"))
                            .to_col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("generation_budgets"))
                    .col(
                        ColumnDef::new(Alias::new("request_id"))
                            .uuid()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("token_limit"))
                            .big_integer()
                            .not_null()
                            .check(Expr::cust("token_limit > 0")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("used_tokens"))
                            .big_integer()
                            .not_null()
                            .default(Expr::cust("0"))
                            .check(Expr::cust(
                                "used_tokens >= 0 AND used_tokens <= token_limit",
                            )),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("generation_budgets"))
                            .from_col(Alias::new("request_id"))
                            .to_tbl(Alias::new("generation_requests"))
                            .to_col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("generation_usage"))
                    .col(ColumnDef::new(Alias::new("request_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("attempt_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("run_id")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("reserved_tokens"))
                            .big_integer()
                            .not_null()
                            .check(Expr::cust("reserved_tokens > 0")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("reported_tokens"))
                            .big_integer()
                            .check(Expr::cust("reported_tokens >= 0")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .primary_key(
                        Index::create()
                            .col(Alias::new("request_id"))
                            .col(Alias::new("attempt_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("generation_usage"))
                            .from_col(Alias::new("request_id"))
                            .to_tbl(Alias::new("generation_requests"))
                            .to_col(Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("generation_usage"))
                            .from_col(Alias::new("run_id"))
                            .to_tbl(Alias::new("runs"))
                            .to_col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("generation_usage"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("generation_budgets"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("generation_history"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("generation_requests_policy")
                    .table(Alias::new("generation_requests"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("generation_requests"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_task_origins"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("generation_policy_history"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("generation_policies"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
