use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		// SeaQuery cannot replace existing CHECK constraints. Extend the strict
		// Registry and package shapes for optional workbench behavior flags.
		for (table, name, expression) in
			super::m20260921_071045_record_constraints::workbench_checks()
		{
			if matches!(name, "registry_agent_config" | "packages_identity") {
				manager.get_connection().execute_unprepared(&format!(
					"ALTER TABLE \"{table}\" DROP CONSTRAINT \"{name}\", ADD CONSTRAINT \"{name}\" CHECK (COALESCE(({expression}), false))"
				)).await?;
			}
		}
		let drafts = Alias::new("agent_drafts");
		manager
			.create_table(
				Table::create()
					.table(drafts.clone())
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("tenant")).text().not_null())
					.col(ColumnDef::new(Alias::new("owner")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("managed_id"))
							.text()
							.not_null()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(1),
					)
					.col(ColumnDef::new(Alias::new("entry")).json_binary().not_null())
					.col(
						ColumnDef::new(Alias::new("documents"))
							.json_binary()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("release_notes"))
							.text()
							.not_null()
							.default(""),
					)
					.col(ColumnDef::new(Alias::new("source_id")).text())
					.col(ColumnDef::new(Alias::new("source_version")).text())
					.col(
						ColumnDef::new(Alias::new("archived"))
							.boolean()
							.not_null()
							.default(false),
					)
					.col(
						ColumnDef::new(Alias::new("updated_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("agent_drafts_tenant_owner")
					.table(drafts.clone())
					.col(Alias::new("tenant"))
					.col(Alias::new("owner"))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("agent_draft_shares"))
					.col(ColumnDef::new(Alias::new("draft_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("subject")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("can_edit"))
							.boolean()
							.not_null()
							.default(false),
					)
					.col(
						ColumnDef::new(Alias::new("documents_digest"))
							.text()
							.not_null(),
					)
					.primary_key(
						Index::create()
							.col(Alias::new("draft_id"))
							.col(Alias::new("subject")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("agent_draft_shares"))
							.from_col(Alias::new("draft_id"))
							.to_tbl(drafts.clone())
							.to_col(Alias::new("id"))
							.on_delete(ForeignKeyAction::Cascade),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("agent_draft_registrations"))
					.col(ColumnDef::new(Alias::new("draft_id")).uuid().not_null())
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("agent_id")).text().not_null())
					.col(ColumnDef::new(Alias::new("version")).text().not_null())
					.col(ColumnDef::new(Alias::new("actor")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("release_notes"))
							.text()
							.not_null()
							.default(""),
					)
					.col(ColumnDef::new(Alias::new("source_id")).text())
					.col(ColumnDef::new(Alias::new("source_version")).text())
					.col(
						ColumnDef::new(Alias::new("behavioral_tested"))
							.boolean()
							.not_null()
							.default(false),
					)
					.col(
						ColumnDef::new(Alias::new("registered_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.primary_key(
						Index::create()
							.col(Alias::new("draft_id"))
							.col(Alias::new("revision")),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("agent_draft_registrations"))
							.from_col(Alias::new("draft_id"))
							.to_tbl(drafts.clone())
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("agent_draft_registered_version")
					.table(Alias::new("agent_draft_registrations"))
					.unique()
					.col(Alias::new("agent_id"))
					.col(Alias::new("version"))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("agent_test_limits"))
					.col(ColumnDef::new(Alias::new("tenant")).text().primary_key())
					.col(
						ColumnDef::new(Alias::new("max_input_bytes"))
							.integer()
							.not_null()
							.default(20000),
					)
					.col(
						ColumnDef::new(Alias::new("max_output_tokens"))
							.integer()
							.not_null()
							.default(2048),
					)
					.col(
						ColumnDef::new(Alias::new("max_total_tokens"))
							.integer()
							.not_null()
							.default(16384),
					)
					.col(
						ColumnDef::new(Alias::new("max_steps"))
							.integer()
							.not_null()
							.default(12),
					)
					.col(
						ColumnDef::new(Alias::new("max_duration_secs"))
							.integer()
							.not_null()
							.default(60),
					)
					.col(
						ColumnDef::new(Alias::new("max_concurrent"))
							.integer()
							.not_null()
							.default(2),
					)
					.col(
						ColumnDef::new(Alias::new("payload_days"))
							.integer()
							.not_null()
							.default(30),
					)
					.col(
						ColumnDef::new(Alias::new("incident_evidence_days"))
							.integer()
							.not_null()
							.default(90),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("agent_test_profiles"))
					.col(ColumnDef::new(Alias::new("tenant")).text().not_null())
					.col(ColumnDef::new(Alias::new("id")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(1),
					)
					.col(
						ColumnDef::new(Alias::new("enabled"))
							.boolean()
							.not_null()
							.default(true),
					)
					.col(ColumnDef::new(Alias::new("rules")).json_binary().not_null())
					.col(
						ColumnDef::new(Alias::new("updated_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.primary_key(
						Index::create()
							.col(Alias::new("tenant"))
							.col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("agent_test_sessions"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("draft_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("tenant")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("status")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("scenario"))
							.json_binary()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("conversation")).json_binary())
					.col(ColumnDef::new(Alias::new("tool_calls")).json_binary())
					.col(ColumnDef::new(Alias::new("usage")).json_binary().not_null())
					.col(ColumnDef::new(Alias::new("error")).text())
					.col(
						ColumnDef::new(Alias::new("active_slot"))
							.uuid()
							.unique_key(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(
						ColumnDef::new(Alias::new("updated_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(
						ColumnDef::new(Alias::new("expires_at"))
							.timestamp_with_time_zone()
							.not_null(),
					)
					.col(ColumnDef::new(Alias::new("expired_at")).timestamp_with_time_zone())
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("agent_test_sessions"))
							.from_col(Alias::new("draft_id"))
							.to_tbl(drafts.clone())
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("agent_test_sessions_draft_created")
					.table(Alias::new("agent_test_sessions"))
					.col(Alias::new("draft_id"))
					.col(Alias::new("created_at"))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("agent_incidents"))
					.col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
					.col(ColumnDef::new(Alias::new("tenant")).text().not_null())
					.col(ColumnDef::new(Alias::new("agent_id")).text().not_null())
					.col(ColumnDef::new(Alias::new("version")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("revision"))
							.big_integer()
							.not_null()
							.default(1),
					)
					.col(ColumnDef::new(Alias::new("severity")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("status"))
							.text()
							.not_null()
							.default("open"),
					)
					.col(
						ColumnDef::new(Alias::new("archived"))
							.boolean()
							.not_null()
							.default(false),
					)
					.col(ColumnDef::new(Alias::new("owner")).text().not_null())
					.col(ColumnDef::new(Alias::new("notes")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("evidence"))
							.json_binary()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(
						ColumnDef::new(Alias::new("updated_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(ColumnDef::new(Alias::new("resolved_at")).timestamp_with_time_zone())
					.col(
						ColumnDef::new(Alias::new("evidence_expires_at"))
							.timestamp_with_time_zone(),
					)
					.col(
						ColumnDef::new(Alias::new("evidence_expired_at"))
							.timestamp_with_time_zone(),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("agent_incidents_version")
					.table(Alias::new("agent_incidents"))
					.col(Alias::new("agent_id"))
					.col(Alias::new("version"))
					.to_owned(),
			)
			.await?;
		manager
			.create_table(
				Table::create()
					.table(Alias::new("agent_incident_events"))
					.col(
						ColumnDef::new(Alias::new("id"))
							.big_integer()
							.auto_increment()
							.primary_key(),
					)
					.col(ColumnDef::new(Alias::new("incident_id")).uuid().not_null())
					.col(ColumnDef::new(Alias::new("actor")).text().not_null())
					.col(
						ColumnDef::new(Alias::new("change"))
							.json_binary()
							.not_null(),
					)
					.col(
						ColumnDef::new(Alias::new("created_at"))
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.foreign_key(
						ForeignKey::create()
							.from_tbl(Alias::new("agent_incident_events"))
							.from_col(Alias::new("incident_id"))
							.to_tbl(Alias::new("agent_incidents"))
							.to_col(Alias::new("id")),
					)
					.to_owned(),
			)
			.await?;
		// SeaQuery does not express PostgreSQL CREATE TRIGGER. These writes must
		// participate in the same atomic write gate as the Registry.
		for table in [
			"agent_drafts",
			"agent_draft_shares",
			"agent_draft_registrations",
			"agent_test_limits",
			"agent_test_profiles",
			"agent_test_sessions",
			"agent_incidents",
			"agent_incident_events",
		] {
			manager.get_connection().execute_unprepared(&format!("CREATE TRIGGER atomic_write_guard BEFORE INSERT OR UPDATE OR DELETE OR TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION atomic_write_guard()")).await?;
		}
		Ok(())
	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		for table in [
			"agent_incident_events",
			"agent_incidents",
			"agent_test_sessions",
			"agent_test_profiles",
			"agent_test_limits",
			"agent_draft_registrations",
			"agent_draft_shares",
			"agent_drafts",
		] {
			manager
				.drop_table(Table::drop().table(Alias::new(table)).to_owned())
				.await?;
		}
		for (table, name, expression) in super::m20260921_071045_record_constraints::checks(true) {
			if matches!(name, "registry_agent_config" | "packages_identity") {
				manager.get_connection().execute_unprepared(&format!(
					"ALTER TABLE \"{table}\" DROP CONSTRAINT \"{name}\", ADD CONSTRAINT \"{name}\" CHECK (COALESCE(({expression}), false))"
				)).await?;
			}
		}
		Ok(())
	}
}
