use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        if crate::legacy_applied(manager, 5, "5b40d3ea8f402d1ce991c11a9754d1fb965aedc70c87004045d4cc1837442b663f0f6bc7ab816e76dce1fb099e477a10").await? { return Ok(()); }
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_credentials"))
                    .col(ColumnDef::new(Alias::new("id")).uuid().primary_key())
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(ColumnDef::new(Alias::new("subject")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("token_hash"))
                            .binary()
                            .not_null()
                            .unique_key()
                            .check(Expr::cust("octet_length(token_hash) = 32")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("clock_timestamp()")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("expires_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("revoked_at")).timestamp_with_time_zone())
                    .col(ColumnDef::new(Alias::new("issued_by")).text().not_null())
                    .check(Expr::cust("expires_at > created_at"))
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_credentials"))
                            .from_col(Alias::new("tenant"))
                            .to_tbl(Alias::new("authorization_bundles"))
                            .to_col(Alias::new("tenant")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("authorization_credentials_tenant")
                    .table(Alias::new("authorization_credentials"))
                    .col(Alias::new("tenant"))
                    .col(Alias::new("created_at"))
                    .col(Alias::new("id"))
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_workspaces"))
                    .col(
                        ColumnDef::new(Alias::new("workspace_id"))
                            .uuid()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("owner_subject"))
                            .text()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_workspaces"))
                            .from_col(Alias::new("workspace_id"))
                            .to_tbl(Alias::new("workspaces"))
                            .to_col(Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_workspaces"))
                            .from_col(Alias::new("tenant"))
                            .to_tbl(Alias::new("authorization_bundles"))
                            .to_col(Alias::new("tenant")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("authorization_workspaces_tenant")
                    .table(Alias::new("authorization_workspaces"))
                    .col(Alias::new("tenant"))
                    .col(Alias::new("workspace_id"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        crate::ensure_not_legacy(manager, 5).await?;
        manager
            .drop_index(
                Index::drop()
                    .name("authorization_workspaces_tenant")
                    .table(Alias::new("authorization_workspaces"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_workspaces"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("authorization_credentials_tenant")
                    .table(Alias::new("authorization_credentials"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_credentials"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
