use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        if crate::legacy_applied(manager, 6, "bbd6eaeda56cfa0250e162c0b36d2e466c157c11fe821b73bec4e4988bf1c338a7d69596e2836cfdada287d4d4fa3dd5").await? { return Ok(()); }
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_catalog"))
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(ColumnDef::new(Alias::new("entry_id")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("entry_version"))
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("enabled")).boolean().not_null())
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .big_integer()
                            .not_null()
                            .check(Expr::cust("revision > 0")),
                    )
                    .primary_key(
                        Index::create()
                            .col(Alias::new("tenant"))
                            .col(Alias::new("entry_id"))
                            .col(Alias::new("entry_version")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_catalog"))
                            .from_col(Alias::new("tenant"))
                            .to_tbl(Alias::new("authorization_bundles"))
                            .to_col(Alias::new("tenant")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_catalog"))
                            .from_col(Alias::new("entry_id"))
                            .from_col(Alias::new("entry_version"))
                            .to_tbl(Alias::new("registry"))
                            .to_col(Alias::new("id"))
                            .to_col(Alias::new("version")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_catalog_history"))
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(ColumnDef::new(Alias::new("entry_id")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("entry_version"))
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("enabled")).boolean().not_null())
                    .col(ColumnDef::new(Alias::new("actor")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .primary_key(
                        Index::create()
                            .col(Alias::new("tenant"))
                            .col(Alias::new("entry_id"))
                            .col(Alias::new("entry_version"))
                            .col(Alias::new("revision")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_catalog_history"))
                            .from_col(Alias::new("tenant"))
                            .from_col(Alias::new("entry_id"))
                            .from_col(Alias::new("entry_version"))
                            .to_tbl(Alias::new("authorization_catalog"))
                            .to_col(Alias::new("tenant"))
                            .to_col(Alias::new("entry_id"))
                            .to_col(Alias::new("entry_version")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_execution"))
                    .col(ColumnDef::new(Alias::new("run_id")).uuid().primary_key())
                    .col(
                        ColumnDef::new(Alias::new("task_id"))
                            .uuid()
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Alias::new("workspace_id")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("credential_id"))
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("root_subject")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("subject_chain"))
                            .array(ColumnType::Text)
                            .not_null()
                            .check(Expr::cust("cardinality(subject_chain) BETWEEN 2 AND 32")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_execution"))
                            .from_col(Alias::new("run_id"))
                            .to_tbl(Alias::new("runs"))
                            .to_col(Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_execution"))
                            .from_col(Alias::new("task_id"))
                            .to_tbl(Alias::new("tasks"))
                            .to_col(Alias::new("id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_execution"))
                            .from_col(Alias::new("workspace_id"))
                            .to_tbl(Alias::new("authorization_workspaces"))
                            .to_col(Alias::new("workspace_id")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_execution"))
                            .from_col(Alias::new("tenant"))
                            .to_tbl(Alias::new("authorization_bundles"))
                            .to_col(Alias::new("tenant")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_execution"))
                            .from_col(Alias::new("credential_id"))
                            .to_tbl(Alias::new("authorization_credentials"))
                            .to_col(Alias::new("id")),
                    )
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        crate::ensure_not_legacy(manager, 6).await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_execution"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_catalog_history"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_catalog"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
