use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_bundles"))
                    .col(ColumnDef::new(Alias::new("tenant")).text().primary_key())
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .big_integer()
                            .not_null()
                            .check(Expr::cust("revision > 0")),
                    )
                    .col(
                        ColumnDef::new(Alias::new("document"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_revisions"))
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("document"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("actor")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .primary_key(
                        Index::create()
                            .col(Alias::new("tenant"))
                            .col(Alias::new("revision")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_revisions"))
                            .from_col(Alias::new("tenant"))
                            .to_tbl(Alias::new("authorization_bundles"))
                            .to_col(Alias::new("tenant")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("authorization_decisions"))
                    .col(
                        ColumnDef::new(Alias::new("sequence"))
                            .big_integer()
                            .primary_key()
                            .extra("GENERATED ALWAYS AS IDENTITY".to_owned()),
                    )
                    .col(ColumnDef::new(Alias::new("tenant")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("revision"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("subject")).text().not_null())
                    .col(ColumnDef::new(Alias::new("action")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("resource_kind"))
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("resource_id")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("decision"))
                            .json_binary()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::cust("now()")),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from_tbl(Alias::new("authorization_decisions"))
                            .from_col(Alias::new("tenant"))
                            .from_col(Alias::new("revision"))
                            .to_tbl(Alias::new("authorization_revisions"))
                            .to_col(Alias::new("tenant"))
                            .to_col(Alias::new("revision")),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("authorization_decisions_tenant")
                    .table(Alias::new("authorization_decisions"))
                    .col(Alias::new("tenant"))
                    .col(Alias::new("sequence"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_index(
                Index::drop()
                    .name("authorization_decisions_tenant")
                    .table(Alias::new("authorization_decisions"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_decisions"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_revisions"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Alias::new("authorization_bundles"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
