use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;
fn c(name: &str) -> ColumnDef {
	ColumnDef::new(Alias::new(name))
}

const TABLES: &[&str] = &[
	"semantic_remote_operations",
	"semantic_remote_attempts",
	"semantic_remote_reads",
	"semantic_remote_receipts",
	"generation_remote_usage",
	"generation_remote_finalizations",
	"generation_remote_dispatches",
];

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, m: &SchemaManager) -> Result<(), DbErr> {
		m.alter_table(
			Table::alter()
				.table(Alias::new("authorization_remote_grants"))
				.add_column(
					c("semantic")
						.json_binary()
						.not_null()
						.default(Expr::cust("'{\"mode\":\"disabled\"}'::jsonb")),
				)
				.to_owned(),
		)
		.await?;
		m.alter_table(
			Table::alter()
				.table(Alias::new("generation_requests"))
				.add_column(c("retired_catalog_revision").big_integer())
				.to_owned(),
		)
		.await?;
		// Operations and usage have explicit cross-node bindings, not foreign keys
		// to a fictional local Run or Task on the other node.
		m.create_table(
			Table::create()
				.table(Alias::new(TABLES[0]))
				.col(c("id").uuid().not_null().primary_key())
				.col(c("home_node").text().not_null())
				.col(c("grant_id").uuid().not_null())
				.col(c("admission_id").uuid().not_null())
				.col(c("digest").text().not_null())
				.col(c("binding").json_binary().not_null())
				.col(c("state").text().not_null().default("PENDING").check(
					Expr::col(Alias::new("state")).is_in([
						"PENDING",
						"ACTIVE",
						"WAITING",
						"READY",
						"PAUSED",
						"INVALIDATED",
						"CANCELLED",
					]),
				))
				.col(c("cycle").integer().not_null().default(0))
				.col(c("failures").integer().not_null().default(0))
				.col(c("attempt_id").uuid())
				.col(c("fence").big_integer().not_null().default(0))
				.col(c("lease_until").timestamp_with_time_zone())
				.col(c("next_attempt").timestamp_with_time_zone())
				.col(c("error").text())
				.col(c("receipt").json_binary())
				.col(
					c("created_at")
						.timestamp_with_time_zone()
						.not_null()
						.default(Expr::current_timestamp()),
				)
				.to_owned(),
		)
		.await?;
		m.create_index(
			Index::create()
				.name("semantic_remote_operation_run")
				.table(Alias::new(TABLES[0]))
				.col(Alias::new("home_node"))
				.col(Alias::new("grant_id"))
				.col(Alias::new("admission_id"))
				.to_owned(),
		)
		.await?;
		m.create_table(
			Table::create()
				.table(Alias::new(TABLES[1]))
				.col(c("id").uuid().not_null().primary_key())
				.col(c("operation_id").uuid().not_null())
				.col(c("fence").big_integer().not_null())
				.col(c("cycle").integer().not_null())
				.col(
					c("state")
						.text()
						.not_null()
						.check(Expr::col(Alias::new("state")).is_in([
							"RESERVING",
							"DISPATCHED",
							"COMPLETED",
							"ABORTED",
							"UNCERTAIN",
						])),
				)
				.col(
					c("reservations")
						.json_binary()
						.not_null()
						.default(Expr::cust("'[]'::jsonb")),
				)
				.col(c("error").text())
				.col(
					c("created_at")
						.timestamp_with_time_zone()
						.not_null()
						.default(Expr::current_timestamp()),
				)
				.col(c("dispatched_at").timestamp_with_time_zone())
				.col(c("completed_at").timestamp_with_time_zone())
				.to_owned(),
		)
		.await?;
		m.create_table(
			Table::create()
				.table(Alias::new(TABLES[2]))
				.col(c("grant_id").uuid().not_null())
				.col(c("admission_id").uuid().not_null())
				.col(c("entry_id").uuid().not_null())
				.col(c("revision").big_integer().not_null())
				.col(c("content_digest").text().not_null())
				.primary_key(
					Index::create()
						.col(Alias::new("grant_id"))
						.col(Alias::new("admission_id"))
						.col(Alias::new("entry_id"))
						.col(Alias::new("revision")),
				)
				.to_owned(),
		)
		.await?;
		m.create_table(
			Table::create()
				.table(Alias::new(TABLES[3]))
				.col(c("operation_id").uuid().not_null().primary_key())
				.col(c("run_id").uuid().not_null())
				.col(c("digest").text().not_null())
				.col(c("receipt").json_binary().not_null())
				.col(
					c("created_at")
						.timestamp_with_time_zone()
						.not_null()
						.default(Expr::current_timestamp()),
				)
				.to_owned(),
		)
		.await?;
		m.create_index(
			Index::create()
				.name("semantic_remote_receipts_run")
				.table(Alias::new(TABLES[3]))
				.col(Alias::new("run_id"))
				.to_owned(),
		)
		.await?;
		m.create_table(
			Table::create()
				.table(Alias::new(TABLES[4]))
				.col(c("request_id").uuid().not_null())
				.col(c("attempt_id").uuid().not_null())
				.col(c("operation_id").uuid().not_null())
				.col(c("dispatcher_node").text().not_null())
				.col(c("grant_id").uuid().not_null())
				.col(c("admission_id").uuid().not_null())
				.col(c("purpose").text().not_null().check(
					Expr::col(Alias::new("purpose")).is_in([
						"embedding",
						"inference",
						"compaction",
					]),
				))
				.col(c("digest").text().not_null())
				.col(
					c("reserved_tokens")
						.big_integer()
						.not_null()
						.check(Expr::cust("reserved_tokens >= 0")),
				)
				.col(c("reported_tokens").big_integer())
				.col(c("state").text().not_null().default("RESERVED").check(
					Expr::col(Alias::new("state")).is_in(["RESERVED", "SETTLED", "RELEASED"]),
				))
				.col(
					c("created_at")
						.timestamp_with_time_zone()
						.not_null()
						.default(Expr::current_timestamp()),
				)
				.primary_key(
					Index::create()
						.col(Alias::new("request_id"))
						.col(Alias::new("attempt_id")),
				)
				.to_owned(),
		)
		.await?;
		m.create_index(
			Index::create()
				.name("generation_remote_usage_attempt_digest")
				.table(Alias::new("generation_remote_usage"))
				.col(Alias::new("attempt_id"))
				.col(Alias::new("digest"))
				.to_owned(),
		)
		.await?;
		m.create_table(
			Table::create()
				.table(Alias::new("generation_remote_finalizations"))
				.col(c("attempt_id").uuid().not_null().primary_key())
				.col(c("digest").text().not_null())
				.col(c("result").json_binary())
				.to_owned(),
		)
		.await?;
		m.create_table(
			Table::create()
				.table(Alias::new("generation_remote_dispatches"))
				.col(c("attempt_id").uuid().not_null().primary_key())
				.col(c("usage").json_binary().not_null())
				.col(c("digest").text().not_null())
				.col(c("peer_node").text().not_null())
				.col(c("boundary").json_binary().not_null())
				.col(c("state").text().not_null().default("PREPARING").check(
					Expr::col(Alias::new("state")).is_in([
						"PREPARING",
						"DISPATCHED",
						"SETTLED",
						"ABORTED",
					]),
				))
				.col(
					c("reservations")
						.json_binary()
						.not_null()
						.default(Expr::cust("'[]'::jsonb")),
				)
				.col(c("finalization").json_binary())
				.col(c("peer_finalized").boolean().not_null().default(false))
				.col(
					c("created_at")
						.timestamp_with_time_zone()
						.not_null()
						.default(Expr::current_timestamp()),
				)
				.to_owned(),
		)
		.await?;
		m.create_index(
			Index::create()
				.name("generation_remote_dispatches_preparing")
				.table(Alias::new("generation_remote_dispatches"))
				.col(Alias::new("created_at"))
				.and_where(Expr::col(Alias::new("state")).eq("PREPARING"))
				.to_owned(),
		)
		.await?;
		m.create_index(
			Index::create()
				.name("generation_remote_dispatches_pending_finalization")
				.table(Alias::new("generation_remote_dispatches"))
				.col(Alias::new("created_at"))
				.and_where(Expr::col(Alias::new("state")).is_in(["ABORTED", "SETTLED"]))
				.and_where(Expr::col(Alias::new("peer_finalized")).eq(false))
				.to_owned(),
		)
		.await?;
		for table in TABLES {
			// PostgreSQL statement-trigger DDL has no SeaQuery representation.
			m.get_connection().execute_unprepared(&format!("CREATE TRIGGER atomic_write_guard BEFORE INSERT OR UPDATE OR DELETE OR TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION atomic_write_guard()")).await?;
		}
		Ok(())
	}
	async fn down(&self, m: &SchemaManager) -> Result<(), DbErr> {
		for table in TABLES.iter().rev() {
			m.drop_table(Table::drop().table(Alias::new(*table)).to_owned())
				.await?;
		}
		m.alter_table(
			Table::alter()
				.table(Alias::new("generation_requests"))
				.drop_column(Alias::new("retired_catalog_revision"))
				.to_owned(),
		)
		.await?;
		m.alter_table(
			Table::alter()
				.table(Alias::new("authorization_remote_grants"))
				.drop_column(Alias::new("semantic"))
				.to_owned(),
		)
		.await?;
		Ok(())
	}
}
