//! Application route registration and identity boundaries.
use super::views::management;
use crate::apps::identity::services::boundary::AccessBoundary;
use reinhardt::UnifiedRouter;
pub fn url_patterns() -> UnifiedRouter {
	UnifiedRouter::new().server(|server| {
		server
			.endpoint(management::browse)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::detail)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::publish)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::sources)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::install)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::share)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::consent)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::read_consent)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::list_installations)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::installation)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::configure)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(management::compatibility)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(management::set_compatibility)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(management::activate)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(management::adopt)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(management::approve_set)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(management::host_packages)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(management::administration)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(management::publication_access)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
	})
}
