//! Application endpoint registration and access policies.
use super::views::entries;
use crate::apps::identity::services::boundary::AccessBoundary;
use reinhardt::UnifiedRouter;

pub fn url_patterns() -> UnifiedRouter {
	UnifiedRouter::new().server(|server| {
		server
			.endpoint(super::views::memory::participants)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::memory::assign)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::memory::assignment)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::memory::operate)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::memory::upgrade)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::memory::units)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::memory::mutate)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::memory::participant)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(super::views::peer::query)
			.with_route_middleware(AccessBoundary::peer().with_visibility())
			.endpoint(super::views::peer::verify)
			.with_route_middleware(AccessBoundary::peer().with_visibility())
			.endpoint(super::views::provenance::run_receipt)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::configure)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
			.endpoint(entries::index)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::put)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::entries)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::delete)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::reindex)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::search)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::history)
			.with_route_middleware(AccessBoundary::authenticated().with_visibility())
			.endpoint(entries::cleanup)
			.with_route_middleware(AccessBoundary::operator().with_visibility())
	})
}
