// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0007_model_state", "operations")
		.add_dependency("marketplace", "0007_model_state")
		.atomic(true)
		.with_initial(None)
		.state_only(true)
		.database_only(false)
}
