SET LOCAL search_path = public, pg_catalog;

CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_draft_registrations FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_draft_shares FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_drafts FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_incident_events FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_incidents FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_knowledge FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_test_limits FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_test_profiles FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.agent_test_sessions FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.installations FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.packages FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.registry FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER atomic_write_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.registry_requests FOR EACH STATEMENT EXECUTE FUNCTION public.atomic_write_guard();
CREATE TRIGGER installations_config_guard BEFORE INSERT OR UPDATE OF id, version, config ON public.installations FOR EACH ROW EXECUTE FUNCTION public.guard_installation_config();
CREATE TRIGGER installations_registry_writes_lock BEFORE INSERT OR DELETE OR UPDATE ON public.installations FOR EACH STATEMENT EXECUTE FUNCTION public.lock_registry_installation_writes();
CREATE TRIGGER marketplace_overlay_fence BEFORE INSERT OR UPDATE ON public.installations FOR EACH ROW EXECUTE FUNCTION public.marketplace_overlay_fence();
CREATE TRIGGER marketplace_registry_fence BEFORE INSERT OR UPDATE ON public.registry FOR EACH ROW EXECUTE FUNCTION public.marketplace_registry_fence();
CREATE TRIGGER registry_agent_model_refs_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.registry_agent_model_refs FOR EACH STATEMENT EXECUTE FUNCTION public.guard_registry_agent_model_refs();
CREATE TRIGGER registry_agent_model_refs_sync AFTER INSERT OR UPDATE OF id, version, kind, metadata ON public.registry FOR EACH ROW EXECUTE FUNCTION public.sync_registry_agent_model_refs();
CREATE TRIGGER registry_agent_resource_refs_guard BEFORE INSERT OR DELETE OR UPDATE OR TRUNCATE ON public.registry_agent_resource_refs FOR EACH STATEMENT EXECUTE FUNCTION public.guard_registry_agent_resource_refs();
CREATE TRIGGER registry_agent_resource_refs_sync AFTER INSERT OR UPDATE OF id, version, kind, metadata ON public.registry FOR EACH ROW EXECUTE FUNCTION public.sync_registry_agent_resource_refs();
CREATE TRIGGER registry_installation_writes_lock BEFORE INSERT OR DELETE OR UPDATE ON public.registry FOR EACH STATEMENT EXECUTE FUNCTION public.lock_registry_installation_writes();
CREATE TRIGGER registry_installations_config_guard AFTER UPDATE OF id, version, kind, metadata ON public.registry FOR EACH ROW EXECUTE FUNCTION public.validate_registry_installations();
CREATE TRIGGER registry_installations_model_override_guard AFTER DELETE ON public.registry FOR EACH ROW EXECUTE FUNCTION public.validate_registry_installations();
