apiVersion: v2
name: aidash
description: One Aidash node with a separate frontend and independently scalable servers and workers
type: application
version: 0.1.0
appVersion: 0.1.0
kubeVersion: ">=1.30.0-0"
