#!/usr/bin/env python3
"""Real transaction acceptance in a disposable Kubernetes or k3s namespace.

Requires an explicit kubeconfig and image. Reports are append-only per run and
include failed cases. This driver never changes the current kubectl context.
The SQL diagnostics are generated by the `manage diagnostics acceptance` command
using Reinhardt Query.
"""
import argparse
import concurrent.futures
import datetime
import hashlib
import json
import os
import pathlib
import socket
import subprocess
import time
import threading
import urllib.error
import urllib.request
import uuid

ROOT = pathlib.Path(__file__).resolve().parents[1]
PHASES = [("coordinator.submit", False), ("coordinator.vote", False),
          ("coordinator.commit", False), ("coordinator.abort", True),
          ("coordinator.visible", False), ("coordinator.complete", False),
          ("coordinator.complete", True), ("participant.reserve", False),
          ("participant.prepare", False), ("participant.apply", False),
          ("participant.release", False), ("participant.abort", True)]


def now():
    return datetime.datetime.now(datetime.UTC).isoformat()


def source_identity():
    paths = [ROOT / name for name in ["Cargo.toml", "Cargo.lock", "rust-toolchain.toml", "Dockerfile", "server/Cargo.toml"]]
    paths += list((ROOT / "crates").rglob("Cargo.toml"))
    paths += list((ROOT / "crates").rglob("*.rs")) + list((ROOT / "server/src").rglob("*.rs")) + list((ROOT / "server/examples").rglob("*.rs"))
    paths += [path for path in (ROOT / "server/migrations").rglob("*") if path.is_file()]
    paths += list((ROOT / "server/settings").glob("*.example.toml"))
    files = {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
             for path in sorted(paths)}
    return {"files": files, "sha256": hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest()}


class Cluster:
    def __init__(self, args):
        self.args = args
        self.namespace = "aidash-tx-" + uuid.uuid4().hex[:10]
        self.directory = ROOT / ".ignore" / "transaction-acceptance" / self.namespace
        self.directory.mkdir(parents=True)
        self.env = {**os.environ, "KUBECONFIG": str(pathlib.Path(args.kubeconfig).resolve())}
        self.token = uuid.uuid4().hex
        self.peer_tokens = [uuid.uuid4().hex for _ in range(16)]
        self.forwards = {}
        self.forward_lock = threading.RLock()
        self.queries = json.loads(pathlib.Path(args.queries).read_text())
        self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=4)
        self.created = False

    def kube(self, *args, value=None, check=True):
        return subprocess.run(["kubectl", "-n", self.namespace, *args],
                              input=json.dumps(value) if isinstance(value, dict) else value,
                              capture_output=True, text=True, env=self.env, check=check)

    def apply(self, value):
        self.kube("apply", "-f", "-", value=value)

    def pods(self, selector):
        return json.loads(self.kube("get", "pods", "-l", selector, "-o", "json").stdout)["items"]

    def rollout(self, name, kind="deployment"):
        self.kube("rollout", "status", f"{kind}/{name}", "--timeout=180s")
        # A port-forward remains pinned to its original Pod even after Service
        # endpoints change. Never submit to a terminating Pod's old fault config.
        if name.startswith("tx-") and name.endswith("-server"):
            with self.forward_lock:
                previous = self.forwards.pop(int(name.split("-")[1]), None)
                if previous:
                    previous[0].terminate()
                    previous[0].wait(timeout=10)
                    previous[2].close()

    def forward(self, node):
        with self.forward_lock:
            return self.forward_locked(node)

    def forward_locked(self, node):
        previous = self.forwards.get(node)
        if previous and previous[0].poll() is None:
            return previous[1]
        if previous:
            self.forwards.pop(node)
            previous[0].wait(timeout=10)
            previous[2].close()
        with socket.socket() as listener:
            listener.bind(("127.0.0.1", 0))
            port = listener.getsockname()[1]
        log = (self.directory / f"forward-{node}.log").open("a")
        try:
            process = subprocess.Popen(["kubectl", "-n", self.namespace, "port-forward",
                                        f"service/tx-{node}", f"{port}:8080"],
                                       env=self.env, stdout=log, stderr=log)
        except OSError:
            log.close()
            raise
        self.forwards[node] = (process, f"http://127.0.0.1:{port}", log)
        # kubectl startup can exceed a fixed sleep under the 16-Node matrix.
        # Wait before sending any HTTP request; never retry an ambiguous POST.
        deadline = time.monotonic() + 10
        try:
            while time.monotonic() < deadline:
                if process.poll() is not None:
                    raise ConnectionError(f"port-forward for Node {node} exited before listening")
                try:
                    with socket.create_connection(("127.0.0.1", port), timeout=0.2):
                        return self.forwards[node][1]
                except OSError:
                    time.sleep(0.05)
            raise TimeoutError(f"port-forward for Node {node} did not listen within 10 seconds")
        except BaseException:
            self.forwards.pop(node, None)
            try:
                process.terminate()
                try:
                    process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=10)
            finally:
                log.close()
            raise

    def api(self, node, path, body=None):
        request = urllib.request.Request(self.forward(node) + path,
            data=None if body is None else json.dumps(body).encode(),
            headers={"Authorization": f"Bearer {self.token}", "Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(request, timeout=10) as response:
                return response.status, json.load(response)
        except urllib.error.HTTPError as error:
            return error.code, json.load(error)
        except (OSError, urllib.error.URLError):
            with self.forward_lock:
                previous = self.forwards.pop(node, None)
                if previous:
                    previous[0].terminate()
                    previous[0].wait(timeout=10)
                    previous[2].close()
            raise

    def ready(self, node):
        self.until(lambda: self.api(node, "/health")[0] == 200, "Node health")

    @staticmethod
    def until(predicate, label, timeout=180):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            try:
                if predicate():
                    return
            except (OSError, urllib.error.URLError, subprocess.CalledProcessError):
                pass
            time.sleep(0.1)
        raise AssertionError(f"Timed out: {label}")

    def service(self, name, port, selector):
        self.apply({"apiVersion": "v1", "kind": "Service", "metadata": {"name": name},
                    "spec": {"selector": selector, "ports": [{"port": port, "targetPort": port}]}})

    def provision(self, count):
        self.kube("create", "namespace", self.namespace)
        self.created = True
        version = json.loads(self.kube("version", "-o", "json").stdout)["serverVersion"]["gitVersion"]
        if ("k3s" in version) != (self.args.distribution == "k3s"):
            raise AssertionError(f"Distribution label disagrees with server version {version}")
        source = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
        dirty = bool(subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True))
        identity = source_identity()
        (self.directory / "source-inputs.json").write_text(json.dumps(identity, indent=2))
        (self.directory / "environment.json").write_text(json.dumps({"source_revision": source,
            "dirty": dirty, "source_inputs_sha256": identity["sha256"], "distribution": self.args.distribution, "server_version": version,
            "image": self.args.image, "namespace": self.namespace, "started_at": now(),
            "nodes": count, "repetitions": self.args.repetitions,
            "scope": "selected cases" if self.args.phase or self.args.lifecycle else "transaction process and lifecycle cases",
            "selected_phase": self.args.phase, "selected_lifecycles": self.args.lifecycle,
            "selected_node_counts": self.args.nodes,
            "mixed_version": "not tested; requires a distinct compatible runtime pair"}, indent=2))
        postgres = {"name": "postgres", "image": self.args.postgres_image, "imagePullPolicy": "IfNotPresent",
            "args": ["-c", "max_connections=600"], "env": [{"name": "POSTGRES_USER", "value": "aidash"},
            {"name": "POSTGRES_PASSWORD", "value": self.token}, {"name": "POSTGRES_DB", "value": "aidash_a"}],
            "ports": [{"containerPort": 5432}], "volumeMounts": [{"name": "data", "mountPath": "/var/lib/postgresql/data"}],
            "readinessProbe": {"exec": {"command": ["pg_isready", "-h", "127.0.0.1", "-U", "aidash", "-d", "aidash_a"]}, "periodSeconds": 2}}
        self.apply({"apiVersion": "apps/v1", "kind": "StatefulSet", "metadata": {"name": "postgres"},
            "spec": {"serviceName": "postgres", "replicas": 1, "selector": {"matchLabels": {"app": "postgres"}},
            "template": {"metadata": {"labels": {"app": "postgres"}}, "spec": {"containers": [postgres]}},
            "volumeClaimTemplates": [{"metadata": {"name": "data"}, "spec": {"accessModes": ["ReadWriteOnce"],
            "resources": {"requests": {"storage": "4Gi"}}}}]}})
        self.service("postgres", 5432, {"app": "postgres"})
        self.apply({"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": "nats"},
            "spec": {"replicas": 1, "selector": {"matchLabels": {"app": "nats"}}, "template": {
            "metadata": {"labels": {"app": "nats"}}, "spec": {"containers": [{"name": "nats",
            "image": "nats:2.12-alpine", "args": ["-js"], "ports": [{"containerPort": 4222}]}]}}}})
        self.service("nats", 4222, {"app": "nats"})
        self.rollout("postgres", "statefulset")
        self.rollout("nats")
        for node in range(count):
            password = uuid.uuid4().hex
            # CREATE ROLE/DATABASE are administrative fixture DDL not supported
            # by SeaQuery's application-schema builders. No runtime cross-DB reads.
            self.kube("exec", "-i", "postgres-0", "--", "psql", "-U", "aidash", "-d", "postgres",
                "-v", "ON_ERROR_STOP=1", "-f", "-", value=f"CREATE ROLE tx_{node} LOGIN PASSWORD '{password}';\nCREATE DATABASE tx_{node} OWNER tx_{node};\n")
            self.apply({"apiVersion": "v1", "kind": "Secret", "metadata": {"name": f"tx-{node}"},
                "stringData": {"DATABASE_URL": f"postgres://tx_{node}:{password}@postgres:5432/tx_{node}",
                "AIDASH_API_TOKEN": self.token, **{f"AIDASH_SECRET_TRANSACTION_{peer:02}": self.peer_tokens[peer] for peer in (range(1, count) if node == 0 else [node])}}})
            for role, replicas in [("server", 1), ("worker", 0)]:
                name = f"tx-{node}-{role}"
                labels = {"app": f"tx-{node}", "role": role}
                self.apply({"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": name},
                    "spec": {"replicas": replicas, "selector": {"matchLabels": labels}, "template": {
                    "metadata": {"labels": labels}, "spec": {"automountServiceAccountToken": False,
                    "terminationGracePeriodSeconds": 25, "containers": [{"name": "aidash", "image": self.args.image,
                    "imagePullPolicy": "IfNotPresent", "args": [role], "ports": [{"containerPort": 8080}],
                    "envFrom": [{"secretRef": {"name": f"tx-{node}"}}], "env": [
                    {"name": "AIDASH_NODE_ID", "value": f"aidash://tx-{node:02}"},
                    {"name": "AIDASH_ENDPOINT", "value": f"http://tx-{node}:8080"},
                    {"name": "NATS_URL", "value": "nats://nats:4222"}, {"name": "RUST_LOG", "value": "aidash=warn"},
                    {"name": "AIDASH_API_RATE_BURST", "value": "100000"}, {"name": "AIDASH_AUTH_RATE_BURST", "value": "100000"}],
                    "resources": {"requests": {"cpu": "50m", "memory": "128Mi"}},
                    **({"readinessProbe": {"httpGet": {"path": "/health", "port": 8080}, "periodSeconds": 1}} if role == "server" else {})}]}}}})
            self.service(f"tx-{node}", 8080, {"app": f"tx-{node}", "role": "server"})
        for node in range(count):
            self.rollout(f"tx-{node}-server")
            self.ready(node)
        images = [(pod["metadata"]["name"], [c.get("imageID") for c in pod.get("status", {}).get("containerStatuses", [])]) for pod in self.pods("role")]
        (self.directory / "images.json").write_text(json.dumps(images, indent=2))
        for node in range(1, count):
            for local, remote in [(0, node), (node, 0)]:
                # Pod readiness precedes Service endpoint/DNS propagation. Peer
                # registration performs an HTTP identity check from this Pod.
                self.until(lambda local=local, remote=remote: self.kube("exec", f"deployment/tx-{local}-server", "--", "curl",
                    "--fail", "--silent", "--max-time", "5", "--output", "/dev/null",
                    f"http://tx-{remote}:8080/.well-known/aidash", check=False).returncode == 0,
                    "peer Service identity readiness")
                status, response = self.api(local, "/api/peers", {"node_id": f"aidash://tx-{remote:02}", "endpoint": f"http://tx-{remote}:8080",
                    "credential_env": f"AIDASH_SECRET_TRANSACTION_{max(local, remote):02}", "protocol_version": "0.1", "enabled": True})
                assert status == 200, (local, remote, status, response)
                assert self.api(local, "/api/transactions/trust", {"node_id": f"aidash://tx-{remote:02}", "enabled": True})[0] == 200

    def inspect(self, node, transaction, workspace, key):
        result = self.kube("exec", "-i", "postgres-0", "--", "psql", "-U", "aidash", "-d", f"tx_{node}",
            "-qAt", "-v", "ON_ERROR_STOP=1", "-v", f"transaction={transaction}", "-v", f"workspace={workspace}",
            "-f", "-", value=self.queries[key] + ";\n")
        return [json.loads(line) for line in result.stdout.splitlines() if line.strip()]

    def observe(self, count, transaction, workspaces, observations):
        verified_new_state = any(entry.get("revision") == 1 for entry in observations)
        for node in range(count):
            try:
                status, body = self.api(node, f"/api/workspaces/{workspaces[node]}")
            except (OSError, urllib.error.URLError):
                observations.append({"time": now(), "node": node, "status": "unavailable"})
                continue
            entry = {"time": now(), "node": node, "status": status}
            assert status in (200, 503), entry
            if status == 200:
                revision = body["workspace"]["revision"]
                assert revision in (0, 1)
                entry["revision"] = revision
                observations.append(entry)
                assert not (verified_new_state and revision == 0), "old state after publication"
                if revision == 1 and not verified_new_state:
                    for other in range(count):
                        assert self.inspect(other, transaction, workspaces[other], "tx_workspace")[0]["revision"] == 1, "partial visibility"
                    # Once all participants durably applied this immutable
                    # manifest, they cannot go back. Avoid quadratic diagnostic
                    # traffic while still checking every ordinary response.
                    verified_new_state = True
            else:
                observations.append(entry)

    def case(self, count, phase, edge, abort, repetition, lifecycle=None):
        transaction = str(uuid.uuid4())
        record = {"transaction": transaction, "nodes": count, "phase": phase, "edge": edge,
                  "abort": abort, "repetition": repetition, "lifecycle": lifecycle, "started_at": now(), "result": "failed"}
        trace = []
        owner = 1 if phase.startswith("participant.") else 0
        point = f"{phase}.{edge}"
        name = f"tx-{owner}-server"
        try:
            workspaces = []
            for node in range(count):
                status, body = self.api(node, "/api/workspaces", {"title": "Transaction acceptance", "goal": "Fixed atomic state"})
                assert status == 200, status
                workspaces.append(body["id"])
            manifest = {"id": transaction, "coordinator": "aidash://tx-00", "isolation": "serializable",
                "deadline": (datetime.datetime.now(datetime.UTC) + datetime.timedelta(minutes=10)).isoformat(),
                "participants": [{"node_id": f"aidash://tx-{node:02}", "mutations": [{"kind": "workspace_state", "workspace_id": workspaces[node],
                "expected_revision": 99 if abort and node == count - 1 else 0, "state": {"committed": True}}]} for node in range(count)]}
            self.kube("set", "env", f"deployment/{name}", f"AIDASH_TRANSACTION_FAULT={transaction}:{point}", "AIDASH_TRANSACTION_FAULT_DIR=/tmp")
            self.rollout(name)
            self.ready(owner)
            submission = self.executor.submit(self.api, 0, "/api/transactions", manifest)
            marker = f"/tmp/{transaction}.{point}.reached"
            held = None

            def reached():
                nonlocal held
                self.observe(count, transaction, workspaces, trace)
                for pod in self.pods(f"app=tx-{owner},role=server"):
                    pod_name = pod["metadata"]["name"]
                    if self.kube("exec", pod_name, "--", "test", "-f", marker, check=False).returncode == 0:
                        held = pod_name
                        return True
                return False

            self.until(reached, f"durable cut {point}")
            record["cut_reached_at"] = now()
            self.observe(count, transaction, workspaces, trace)
            if lifecycle == "scale":
                for node in range(count):
                    self.kube("scale", f"deployment/tx-{node}-worker", "--replicas=2")
                    self.rollout(f"tx-{node}-worker")
                for node in range(count):
                    self.kube("scale", f"deployment/tx-{node}-worker", "--replicas=0")
                for node in range(count):
                    self.kube("wait", "--for=delete", "pod", "-l", f"app=tx-{node},role=worker", "--timeout=90s")
                record["workers_at_zero"] = all(not self.pods(f"app=tx-{node},role=worker") for node in range(count))
                assert record["workers_at_zero"]
            elif lifecycle == "peer-recovery":
                for local, remote in [(0, 1), (1, 0)]:
                    assert self.api(local, "/api/transactions/trust", {"node_id": f"aidash://tx-{remote:02}", "enabled": False})[0] == 200
                # Fault injection uses generated SeaQuery DML and the same narrow
                # authority control used by the operator recovery route.
                self.kube("exec", "-i", "postgres-0", "--", "psql", "-U", "aidash", "-d", "tx_0",
                    "-qAt", "-v", "ON_ERROR_STOP=1", "-f", "-", value="BEGIN;\n" +
                    self.queries["tx_authority_control"] + ";\n" + self.queries["tx_disable_peer"] + ";\nCOMMIT;\n")
                assert not self.inspect(0, transaction, workspaces[0], "tx_peer")[0]["enabled"]
                record["peer_transport_disabled_at"] = now()
            elif lifecycle == "rolling":
                for node in range(1, count):
                    self.kube("rollout", "restart", f"deployment/tx-{node}-server")
                    self.rollout(f"tx-{node}-server")
            elif lifecycle == "partition":
                self.kube("scale", "deployment/tx-1-server", "--replicas=0")
                self.kube("wait", "--for=delete", "pod", "-l", "app=tx-1,role=server", "--timeout=90s")
            record["fault_at"] = now()
            self.kube("set", "env", f"deployment/{name}", "AIDASH_TRANSACTION_FAULT-", "AIDASH_TRANSACTION_FAULT_DIR-")
            self.kube("delete", "pod", held, "--grace-period=0", "--force", "--wait=false", check=False)
            record["fault_removed_at"] = now()
            self.rollout(name)
            self.ready(owner)
            if lifecycle == "partition":
                self.observe(count, transaction, workspaces, trace)
                self.kube("scale", "deployment/tx-1-server", "--replicas=1")
                self.rollout("tx-1-server")
                self.ready(1)
            if lifecycle == "peer-recovery":
                def blocked_by_peer():
                    self.observe(count, transaction, workspaces, trace)
                    status, detail = self.api(0, f"/api/transactions/{transaction}")
                    assert status == 200, (status, detail)
                    state = detail["transaction"]
                    assert not state["complete"], "disabled peer must prevent convergence"
                    return state["decision"] == "COMMIT" and state["last_error"] is not None

                # The process fault is gone. Require an actual failed recovery
                # attempt before restoring transport; a held fault is not proof.
                self.until(blocked_by_peer, "recovery blocked by disabled peer", timeout=30)
                for node in range(count):
                    assert self.api(node, f"/api/workspaces/{workspaces[node]}")[0] == 503
                record["peer_recovery_blocked_at"] = now()
                status, peer = self.api(0, "/api/transactions/peer-recovery", {"node_id": "aidash://tx-01", "credential_env": "AIDASH_SECRET_TRANSACTION_01"})
                assert status == 200, (status, peer)
                assert peer["node_id"] == "aidash://tx-01" and peer["enabled"]
                assert peer["endpoint"] == "http://tx-1:8080"
                assert self.inspect(0, transaction, workspaces[0], "tx_peer")[0]["enabled"]
                _, grants = self.api(0, "/api/transactions/trust")
                assert not next(grant for grant in grants if grant["node_id"] == "aidash://tx-01")["enabled"]
                record["peer_restored_without_admission_trust"] = True
            record["services_restored_at"] = now()
            restored = time.monotonic()
            if not self.inspect(0, transaction, workspaces[0], "tx_coordinator"):
                assert self.api(0, "/api/transactions", manifest)[0] == 202

            def complete():
                self.observe(count, transaction, workspaces, trace)
                status, detail = self.api(0, f"/api/transactions/{transaction}")
                return status == 200 and detail["transaction"]["complete"]

            self.until(complete, "complete decision and barrier release", timeout=180)
            record["completed_at"] = now()
            record["converged_seconds"] = time.monotonic() - restored
            assert record["converged_seconds"] <= 180
            decision = self.inspect(0, transaction, workspaces[0], "tx_coordinator")[0]
            assert decision["decision"] == ("ABORT" if abort else "COMMIT")
            durable = []
            for node in range(count):
                row = {key: self.inspect(node, transaction, workspaces[node], key)
                       for key in ["tx_participant", "tx_barrier", "tx_workspace", "tx_events"]}
                assert row["tx_participant"][0]["phase"] == ("ABORTED" if abort else "COMMITTED")
                assert row["tx_barrier"][0]["transaction_id"] is None
                assert row["tx_workspace"][0]["revision"] == int(not abort)
                assert len(row["tx_events"]) == int(not abort)
                durable.append(row)
            record["durable"] = durable
            if lifecycle == "peer-recovery":
                for local, remote in [(0, 1), (1, 0)]:
                    assert self.api(local, "/api/transactions/trust", {"node_id": f"aidash://tx-{remote:02}", "enabled": True})[0] == 200
            record["result"] = "passed"
            # Lost HTTP replies are expected at submission cuts. They never
            # replace the reconciled durable outcome above.
            if submission.done():
                try:
                    submission.result()
                except (OSError, urllib.error.URLError):
                    pass
        except Exception as error:
            record["error"] = f"{type(error).__name__}: {error}"
            raise
        finally:
            record["observations"] = trace
            with (self.directory / "cases.jsonl").open("a") as output:
                output.write(json.dumps(record) + "\n")
            print(json.dumps({key: record.get(key) for key in ["nodes", "phase", "edge", "abort", "repetition", "lifecycle", "result"]}), flush=True)

    def close(self):
        for process, _, log in self.forwards.values():
            process.terminate()
            process.wait(timeout=10)
            log.close()
        self.executor.shutdown(wait=False, cancel_futures=True)
        if self.created and not self.args.keep:
            self.kube("delete", "namespace", self.namespace, "--wait=true", "--timeout=180s", check=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kubeconfig", required=True)
    parser.add_argument("--distribution", choices=["kubernetes", "k3s"], required=True)
    parser.add_argument("--image", required=True)
    parser.add_argument("--queries", required=True, help="JSON emitted by the Reinhardt Query diagnostics acceptance command")
    parser.add_argument("--postgres-image", default="aidash-postgres:17-pg-jsonschema-0.3.4")
    parser.add_argument("--nodes", nargs="+", type=int, choices=[2, 3, 16], default=[2, 3, 16])
    parser.add_argument("--repetitions", type=int, choices=[3], default=3)
    parser.add_argument("--phase", choices=[phase for phase, _ in PHASES])
    parser.add_argument("--lifecycle", nargs="+", choices=["scale", "rolling", "partition", "peer-recovery"])
    parser.add_argument("--keep", action="store_true")
    args = parser.parse_args()
    if args.phase and args.lifecycle:
        parser.error("select either phase or lifecycle cases")
    cluster = Cluster(args)
    print(f"Evidence: {cluster.directory}", flush=True)
    try:
        cluster.provision(max(args.nodes))
        for count in args.nodes:
            cases = [(phase, edge, abort, None) for phase, abort in PHASES
                     for edge in ["before", "after"] if not args.phase or phase == args.phase]
            if count != 2 and not args.phase:
                cases = [("coordinator.commit", "before", False, "partition"),
                         ("coordinator.abort", "before", True, "partition")]
            if not args.phase:
                cases += [("coordinator.commit", "before", False, lifecycle) for lifecycle in ["scale", "rolling"]]
                if count == 2:
                    cases.append(("coordinator.commit", "before", False, "peer-recovery"))
            if args.lifecycle:
                cases = [case for case in cases if case[3] in args.lifecycle]
            for phase, edge, abort, lifecycle in cases:
                for repetition in range(1, args.repetitions + 1):
                    cluster.case(count, phase, edge, abort, repetition, lifecycle)
    finally:
        cluster.close()


if __name__ == "__main__":
    main()
