// reinhardt-migration-source: 1
// Native schema operations enforce Tenant ownership and catalog/state invariants.
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0013_provider_credential_constraints", "identity")
.add_dependency("identity", "0012_provider_credentials").database_only(true).atomic(true)
.add_operation(Operation::AddConstraintDefinition {table:"provider_credentials".to_owned(),constraint:Constraint::Check {name:"provider_credential_catalog".to_owned(),expression:r#"provider = 'openrouter' AND base_url = 'https://openrouter.ai/api/v1'"#.to_owned()}})
.add_operation(Operation::AddConstraintDefinition {table:"provider_credentials".to_owned(),constraint:Constraint::Check {name:"provider_credential_state".to_owned(),expression:r#"state IN ('pending','active','revoked','deleted') AND (state <> 'active' OR pinned_version IS NOT NULL) AND (state <> 'pending' OR pinned_version IS NULL) AND (state <> 'revoked' OR revoked_at IS NOT NULL)"#.to_owned()}})
.add_operation(Operation::AddConstraintDefinition {table:"provider_credentials".to_owned(),constraint:Constraint::Check {name:"provider_credential_metadata".to_owned(),expression:r#"revision > 0 AND id::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' AND fingerprint ~ '^[0-9a-f]{16}$' AND length(last4) = 4 AND length(tenant) BETWEEN 1 AND 256"#.to_owned()}})
.add_operation(Operation::AddConstraintDefinition {table:"provider_credentials".to_owned(),constraint:Constraint::Check {name:"provider_credential_pin".to_owned(),expression:r#"pinned_version IS NULL OR (pinned_version ~ '/versions/[1-9][0-9]*$' AND left(pinned_version,length(secret_resource)+10) = secret_resource || '/versions/')"#.to_owned()}})
.add_operation(Operation::AddConstraintDefinition {table:"provider_credential_bindings".to_owned(),constraint:Constraint::Check {name:"provider_credential_binding_identity".to_owned(),expression:r#"id = tenant || ':' || provider AND provider = 'openrouter' AND revision > 0"#.to_owned()}})
.add_operation(Operation::AddConstraintDefinition {table:"run_provider_credentials".to_owned(),constraint:Constraint::Check {name:"run_provider_credential_identity".to_owned(),expression:r#"id = run_id::text || ':' || provider AND provider = 'openrouter'"#.to_owned()}})
.add_operation(Operation::AddConstraintDefinition {table:"provider_credentials".to_owned(),constraint:Constraint::Unique {name:"provider_credential_tenant_provider_id".to_owned(),columns:vec!["tenant".to_owned(),"provider".to_owned(),"id".to_owned()]}})
.add_operation(Operation::AddConstraintDefinition {table:"provider_credential_bindings".to_owned(),constraint:Constraint::ForeignKey {name:"provider_credential_bindings_tenant_target".to_owned(),columns:vec!["tenant".to_owned(),"provider".to_owned(),"provider_credential_id".to_owned()],referenced_table:"provider_credentials".to_owned(),referenced_columns:vec!["tenant".to_owned(),"provider".to_owned(),"id".to_owned()],on_delete:ForeignKeyAction::NoAction,on_update:ForeignKeyAction::NoAction,deferrable:None}})
.add_operation(Operation::AddConstraintDefinition {table:"run_provider_credentials".to_owned(),constraint:Constraint::ForeignKey {name:"run_provider_credentials_tenant_target".to_owned(),columns:vec!["tenant".to_owned(),"provider".to_owned(),"provider_credential_id".to_owned()],referenced_table:"provider_credentials".to_owned(),referenced_columns:vec!["tenant".to_owned(),"provider".to_owned(),"id".to_owned()],on_delete:ForeignKeyAction::NoAction,on_update:ForeignKeyAction::NoAction,deferrable:None}})
}
