// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0017_display_erasure", "identity")
		.add_operation(Operation::AddColumn {
			table: "dashboard_identities".to_string(),
			column: ColumnDefinition::new("display_erased_at", FieldType::TimestampTz)
				.with_not_null(false)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			mysql_options: None,
		})
		.add_operation(Operation::AddColumn {
			table: "dashboard_identities".to_string(),
			column: ColumnDefinition::new("display_erased_by", FieldType::Text)
				.with_not_null(false)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			mysql_options: None,
		})
		.add_operation(Operation::AddColumn {
			table: "dashboard_identities".to_string(),
			column: ColumnDefinition::new("display_observed_at", FieldType::TimestampTz)
				.with_not_null(false)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			mysql_options: None,
		})
		.add_dependency("identity", "0016_credential_store_state")
		.atomic(true)
		.with_initial(None)
		.state_only(false)
		.database_only(false)
}
