export const marketplaceCopy = {
  "en-US": {
    publicationVersion: "Publication version",
    search: "Search packages",
    previous: "Previous page",
    next: "Next page",
    empty: "No packages available for this search",
    unavailable: "This item is unavailable with your current access",
    operationUnavailable:
      "This operation is unavailable with your current access",
    packages: "Packages",
    installations: "Tenant installations",
    details: "Details",
    install: "Install for this tenant",
    pending: "Installed; awaiting approval",
    active: "Active approved revision",
    retained: "Approved revision retained for existing runs",
    revoked: "Approval withdrawn; new runs are blocked",
    changed: "Configuration change awaiting approval",
    pinned: "Existing runs use their pinned revision",
    configure: "Stage configuration",
    config: "Local configuration (JSON)",
    bindings: "Exact dependency bindings (JSON)",
    publish: "Publish registered source",
    source: "Registered source",
    packageId: "Package identifier",
    author: "Display author",
    publishHelp:
      "Publishes the stored definition. Local installation overrides are excluded. Initial access is limited to this tenant.",
    share: "Update sharing",
    tenants: "Recipient tenants (one per line)",
    consent: "Manage redistribution consent",
    redistributor: "Redistributing tenant",
    consentRevision: "Current consent revision (0 for a new grant)",
    consentHelp:
      "Consent permits onward distribution to the listed tenants. Removing tenants stops future distribution; existing installations remain locally managed.",
    close: "Close",
    retry: "Reload access",
    revision: "Revision",
    activeRevision: "Active revision",
    saved: "Saved",
    conflict: "The revision changed. Reload before applying another change.",
    admin: "Tenant installation approval",
    tenant: "Tenant",
    load: "Load",
    approve: "Approve and activate",
    revoke: "Revoke this revision",
    compatible: "All API instances and workers support Marketplace contract 1",
    enable: "Enable scoped Marketplace",
    disable: "Disable scoped Marketplace",
    rollout: "Scoped Marketplace availability",
    enabled: "Enabled",
    disabled: "Disabled",
    adoption: "Adopt a legacy package",
    legacyId: "Legacy package identifier",
    legacyVersion: "Exact legacy version",
    adopt: "Create pending tenant copy",
    adoptionHelp:
      "Copies the legacy configuration into an independent tenant installation. Fresh approval is required.",
    permission: "Required permissions",
    digest: "Source digest",
    manifest: "Immutable source manifest",
    published: "Package published",
    installed: "Installation prepared",
    dependencies:
      "Prepare dependencies before installation. Nothing is fetched automatically.",
    reviewInstall: "Review and install",
    installHelp:
      "Check the exact digest and requested permissions. The installation stays pending until an operator approves it.",
    cancel: "Cancel",
    colPackage: "Package",
    colKind: "Kind",
    colVersion: "Version",
    colPublisher: "Publisher",
    colPermissions: "Permissions",
    colState: "State",
    noPermissions: "No permissions requested",
    capabilities: "Capabilities",
    sharing: "Sharing",
  },
  "ja-JP": {
    publicationVersion: "公開するバージョン",
    search: "パッケージを検索",
    previous: "前のページ",
    next: "次のページ",
    empty: "この検索で表示できるパッケージはありません",
    unavailable: "現在の権限ではこの項目を利用できません",
    operationUnavailable: "現在の権限ではこの操作を利用できません",
    packages: "パッケージ",
    installations: "テナントの導入一覧",
    details: "詳細",
    install: "このテナントに導入",
    pending: "導入済み・利用承認待ち",
    active: "有効な承認済みrevision",
    retained: "実行中のRun用に保持された承認済みrevision",
    revoked: "承認取消済み・新しいRunは開始できません",
    changed: "設定変更の承認待ち",
    pinned: "実行中のRunは開始時のrevisionを使用します",
    configure: "設定変更を申請",
    config: "ローカル設定（JSON）",
    bindings: "依存関係の正確な参照（JSON）",
    publish: "登録済み定義を公開",
    source: "登録済み定義",
    packageId: "パッケージ識別子",
    author: "表示用の作者名",
    publishHelp:
      "保存済みの定義を公開します。導入先の設定変更は含まれません。初期の公開範囲はこのテナントのみです。",
    share: "共有範囲を更新",
    tenants: "共有先テナント（1行に1件）",
    consent: "再配布の同意を管理",
    redistributor: "再配布するテナント",
    consentRevision: "現在の同意revision（新規は0）",
    consentHelp:
      "一覧のテナントへの再配布を許可します。テナントを削除すると以降の配布を停止します。導入済みのコピーは導入先で管理されます。",
    close: "閉じる",
    retry: "権限を再確認",
    revision: "Revision",
    activeRevision: "有効なrevision",
    saved: "保存しました",
    conflict: "Revisionが更新されました。再読み込み後に変更してください。",
    admin: "テナント導入の承認",
    tenant: "テナント",
    load: "読み込み",
    approve: "承認して有効化",
    revoke: "このrevisionの承認を取り消す",
    compatible:
      "すべてのAPIインスタンスとWorkerがMarketplace契約1に対応しています",
    enable: "テナント別Marketplaceを有効化",
    disable: "テナント別Marketplaceを無効化",
    rollout: "テナント別Marketplaceの提供状態",
    enabled: "有効",
    disabled: "無効",
    adoption: "既存パッケージをテナントに移行",
    legacyId: "既存パッケージ識別子",
    legacyVersion: "既存の正確なバージョン",
    adopt: "承認待ちのテナントコピーを作成",
    adoptionHelp:
      "既存の設定を独立したテナント導入へコピーします。改めて承認が必要です。",
    permission: "必要な権限",
    digest: "配布元のダイジェスト",
    manifest: "不変の配布元マニフェスト",
    published: "パッケージを公開しました",
    installed: "導入を準備しました",
    dependencies: "依存関係は導入前に準備してください。自動取得は行いません。",
    reviewInstall: "確認して導入",
    installHelp:
      "ダイジェストと要求される権限を確認してください。管理者が承認するまで導入は承認待ちのままです。",
    cancel: "キャンセル",
    colPackage: "パッケージ",
    colKind: "種類",
    colVersion: "バージョン",
    colPublisher: "公開元",
    colPermissions: "権限",
    colState: "状態",
    noPermissions: "要求される権限はありません",
    capabilities: "機能",
    sharing: "共有範囲",
  },
} as const;
