export const collaborationCopy = {
  "ja-JP": {
    collaboration: "コラボレーション",
    graph: "Graph View",
    settings: "設定",
    channels: "チャンネル",
    create: "チャンネルを作成",
    prepare: "準備用チャンネル",
    createAndStart: "ゴールを作成して実行",
    noChannel: "チャンネルを選択してください",
    unavailable: "この対象は現在の権限で取得できません。",
    channelHelp: "一つのゴールに向けて、人間とエージェントで会話する場所です。",
    conversation: "会話",
    work: "タスクと成果物",
    activity: "実行履歴",
    goal: "ゴール",
    send: "送信",
    sending: "送信中…",
    message: "メッセージ",
    placeholder: "情報を共有する、質問する…",
    retry: "再試行",
    sent: "送信しました",
    failed: "送信できませんでした。内容は保持しています。",
    tasks: "タスク",
    results: "成果物",
    active: "実行中",
    completed: "完了タスク",
    attention: "対応が必要",
    noMessages: "まだメッセージはありません。",
    downloadAttachment: "添付ファイルをダウンロード",
    downloadFailed: "添付ファイルをダウンロードできませんでした。",
    noTasks: "このチャンネルにはタスクがありません。",
    newTask: "タスクを追加",
    details: "詳細を開く",
    participants: "この仕事のエージェント",
    needsInput: "確認・回答が必要",
    answer: "回答する",
    graphLink: "グラフで確認",
    channelLink: "チャンネルを開く",
    relatedChannels: "関連チャンネル",
    noRelated: "現在取得できる情報には関連チャンネルがありません。",
    graphMode: "グラフ表示の切り替え",
    relationships: "エージェントの関係",
    topology: "ノード構成と通信",
    currentGraph: "現在のグラフ",
    localSnapshot:
      "現在取得できるノード内の関係を表示しています。全ノード・全履歴を表すものではありません。",
    graphFocus: "中心にするエージェント",
    graphList: "関係一覧",
    graphCanvas: "グラフ",
    expand: "周辺を展開",
    filters: "表示する種類",
    runtime: "実行上の関係",
    configuration: "設定上の関係",
    omitted: "表示範囲外",
    home: "チャンネルに戻る",
    search: "チャンネルを検索",
    reconnecting: "再接続中",
    live: "接続中",
    empty: "該当する情報はありません。",
    settingsHelp: "構成・登録・管理はここから操作します。",
    node: "ノードと接続",
    back: "戻る",
    noAgent:
      "閲覧可能なエージェントがありません。設定のRegistryで登録を確認してください。",
    limitedHistory:
      "この表示はAPIが返した履歴の範囲です。過去時点のグラフ復元ではありません。",
    newMessages: "最新のメッセージへ",
    human: "人間",
    agent: "エージェント",
    login: "接続",
    disconnect: "切断",
    taskProgress: "タスク進捗（Goalの完了判定とは別）",
    processing: "処理中…",
    setupNotice: "準備用チャンネルの作成だけではエージェントを起動しません。",
    inferenceProgress: "推論の進捗",
    inferencePending: "生成中",
    inferenceTentative: "未確定の出力です。最終的な応答ではありません。",
    inferenceToolCall: "引数を組み立て中（{bytes} バイト）",
    inferenceUnnamedTool: "ツール #{index}",
    inferenceTruncated: "表示上限に達したため以降の出力を省略しました。",
    inferenceGap: "一部の進捗は保持期間を過ぎたため表示できません。",
    inferenceStarted: "生成を開始しました",
    inferenceAccepted: "応答が確定しました",
    inferenceInterrupted: "中断",
    inferenceReasons: {
      correction: "新しい入力で破棄",
      cancelled: "キャンセル",
      lease_lost: "実行権の喪失",
      stall: "応答停止",
      stream_error: "ストリームエラー",
      revoked: "権限の取り消し",
    },
  },
  "en-US": {
    collaboration: "Collaboration",
    graph: "Graph View",
    settings: "Settings",
    channels: "Channels",
    create: "Create channel",
    prepare: "Prepare a channel",
    createAndStart: "Create and run a goal",
    noChannel: "Choose a channel",
    unavailable: "This resource is unavailable under your current access.",
    channelHelp:
      "A shared conversation for people and agents working toward one goal.",
    conversation: "Conversation",
    work: "Tasks and results",
    activity: "Execution history",
    goal: "Goal",
    send: "Send",
    sending: "Sending…",
    message: "Message",
    placeholder: "Share context or ask a question…",
    retry: "Retry",
    sent: "Message sent",
    failed: "The message could not be sent. Your text has been kept.",
    tasks: "Tasks",
    results: "Artifacts",
    active: "Running",
    completed: "Completed tasks",
    attention: "Needs attention",
    noMessages: "No messages yet.",
    downloadAttachment: "Download attachment",
    downloadFailed: "Could not download the attachment.",
    noTasks: "No tasks in this channel yet.",
    newTask: "Add task",
    details: "Open details",
    participants: "Agents working here",
    needsInput: "Input required",
    answer: "Respond",
    graphLink: "View in graph",
    channelLink: "Open channel",
    relatedChannels: "Related channels",
    noRelated: "No related channels in the currently available information.",
    graphMode: "Graph mode",
    relationships: "Agent relationships",
    topology: "Node topology and communication",
    currentGraph: "Current graph",
    localSnapshot:
      "Relationships in the currently available node snapshot. This is not a complete federated or historical graph.",
    graphFocus: "Focus agent",
    graphList: "Relationship list",
    graphCanvas: "Graph",
    expand: "Expand neighbors",
    filters: "Visible types",
    runtime: "Runtime relationships",
    configuration: "Configuration relationships",
    omitted: "Outside this view",
    home: "Back to channel",
    search: "Search channels",
    reconnecting: "Reconnecting",
    live: "Live",
    empty: "No matching information.",
    settingsHelp: "Configuration, registration and administration.",
    node: "Node and connection",
    back: "Back",
    noAgent: "No readable agents. Check registrations in Settings / Registry.",
    limitedHistory:
      "This view contains history returned by the API. It is not past-time graph reconstruction.",
    newMessages: "Jump to latest messages",
    human: "Human",
    agent: "Agent",
    login: "Connect",
    disconnect: "Disconnect",
    taskProgress: "Task progress (not a goal-completion decision)",
    processing: "Processing…",
    setupNotice: "Preparing a channel does not start an agent.",
    inferenceProgress: "Inference progress",
    inferencePending: "Generating",
    inferenceTentative: "Tentative output; not a final response.",
    inferenceToolCall: "assembling arguments ({bytes} bytes)",
    inferenceUnnamedTool: "Tool #{index}",
    inferenceTruncated: "Later output is omitted after the display limit.",
    inferenceGap: "Some progress expired and is no longer available.",
    inferenceStarted: "Generation started",
    inferenceAccepted: "Response accepted",
    inferenceInterrupted: "Interrupted",
    inferenceReasons: {
      correction: "Discarded by new input",
      cancelled: "Cancelled",
      lease_lost: "Lease lost",
      stall: "Stalled",
      stream_error: "Stream error",
      revoked: "Access revoked",
    },
  },
} as const;
