export const meshCopy = {
  "en-US": {
    subtitle: "People, agents, tasks, and knowledge — connected.",
    modes: {
      mesh: "Agent mesh",
      collaboration: "Collaboration",
      knowledge: "Knowledge graph",
      execution: "Execution flow",
      topology: "Topology",
    },
    kinds: {
      human: "Humans",
      workspace: "Workspaces",
      goal: "Goals",
      conversation: "Conversations",
      task: "Tasks",
      agent: "Agents",
      tool: "Tools",
      artifact: "Artifacts",
      cluster: "Clusters",
      remote: "Nodes",
      model: "Models",
      skill: "Skills",
    },
    relations: {
      contains: "contains",
      goal: "works toward",
      creates: "creates",
      assigned: "assigned to",
      executes: "executes",
      delegates: "delegates",
      depends: "prerequisite for",
      produces: "produces",
      tool: "uses tool",
      model: "uses model",
      skill: "uses skill",
      member: "member of",
      hosts: "hosts",
      coordinates: "coordinates",
      federation: "federation",
      participates: "participates in",
    },
    search: "Search nodes, tasks, agents, or artifacts…",
    mode: "Graph perspective",
    layout: "Layout",
    camera: "Graph navigation",
    mesh: "Structured layout",
    force: "Force layout",
    radial: "Circle layout",
    time: "Activity window",
    allTime: "All available activity",
    hour: "Last hour",
    day: "Last 24 hours",
    week: "Last 7 days",
    month: "Last 30 days",
    types: "Node types",
    advancedTypes: "Models & skills",
    relationsLabel: "Relation types",
    filters: "Filters",
    list: "Relationship list",
    canvas: "Graph canvas",
    overview: "Overview",
    tasks: "Tasks",
    events: "Events",
    config: "Connections",
    about: "About",
    type: "Type",
    version: "Version",
    status: "Status",
    node: "Node",
    model: "Model",
    capabilities: "Capabilities",
    recent: "Recent events",
    activity: "Recorded activity",
    related: "Related channels",
    connected: "Connected nodes",
    noEvents: "No recorded events in this window.",
    noTasks: "No connected tasks.",
    noConnections: "No recorded connections.",
    missing: "Not available in this view",
    noResults: "No matching nodes",
    clear: "Reset filters",
    empty: "Create a workspace or register an agent to start exploring.",
    open: "Open details",
    channel: "Open workspace",
    close: "Close details",
    focus: "Focus neighborhood",
    unfocus: "Show full graph",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    fit: "Fit graph",
    center: "Center selection",
    minimap: "Graph minimap — click to navigate",
    fullscreen: "Toggle fullscreen",
    select: "Node details",
    snapshot: "Authorized snapshot · configured links and recorded activity",
    omitted: "Not shown",
    local: "Local agents",
    tools: "Tools",
    artifacts: "Artifacts",
    external: "External agents",
    unknown: "Status unavailable",
    configured: "Configured",
    discovered: "Discovered",
    localNode: "Local",
    running: "Running tasks",
    blocked: "Blocked tasks",
    completed: "Completed tasks",
    pending: "Open tasks",
    timeline: "Execution timeline",
    noTimeline: "No recorded events in this window",
    more: "More graph options",
    export: "Export graph as PNG",
    fullDetails: "Agent relationships",
    live: "Snapshot updates every 5 seconds",
    counts: "nodes",
    links: "links",
    windowHelp:
      "Filters recorded runs and events. Active runs and current task/configuration state remain visible.",
    noSelection: "Select a node to explore its connections.",
  },
  "ja-JP": {
    subtitle: "人・エージェント・タスク・ナレッジのつながりを可視化。",
    modes: {
      mesh: "エージェントメッシュ",
      collaboration: "コラボレーション",
      knowledge: "ナレッジグラフ",
      execution: "実行フロー",
      topology: "トポロジー",
    },
    kinds: {
      human: "人間",
      workspace: "ワークスペース",
      goal: "ゴール",
      conversation: "会話",
      task: "タスク",
      agent: "エージェント",
      tool: "ツール",
      artifact: "成果物",
      cluster: "クラスター",
      remote: "ノード",
      model: "モデル",
      skill: "スキル",
    },
    relations: {
      contains: "含む",
      goal: "目指す",
      creates: "作成",
      assigned: "担当",
      executes: "実行",
      delegates: "委譲",
      depends: "前提タスク",
      produces: "生成",
      tool: "ツール利用",
      model: "モデル利用",
      skill: "スキル利用",
      member: "所属",
      hosts: "配置",
      coordinates: "統括",
      federation: "フェデレーション",
      participates: "参加",
    },
    search: "ノード・タスク・エージェント・成果物を検索…",
    mode: "グラフの視点",
    layout: "レイアウト",
    camera: "グラフの表示操作",
    mesh: "構造レイアウト",
    force: "力学レイアウト",
    radial: "円形レイアウト",
    time: "アクティビティの期間",
    allTime: "取得済みの全期間",
    hour: "過去1時間",
    day: "過去24時間",
    week: "過去7日間",
    month: "過去30日間",
    types: "ノードの種類",
    advancedTypes: "モデルとスキル",
    relationsLabel: "関係の種類",
    filters: "フィルター",
    list: "関係一覧",
    canvas: "グラフ",
    overview: "概要",
    tasks: "タスク",
    events: "イベント",
    config: "接続",
    about: "基本情報",
    type: "種類",
    version: "バージョン",
    status: "状態",
    node: "ノード",
    model: "モデル",
    capabilities: "ケイパビリティ",
    recent: "最近のイベント",
    activity: "記録された活動",
    related: "関連チャンネル",
    connected: "接続ノード",
    noEvents: "この期間に記録されたイベントはありません。",
    noTasks: "接続されたタスクはありません。",
    noConnections: "記録された接続はありません。",
    missing: "この表示では取得できません",
    noResults: "一致するノードはありません",
    clear: "絞り込みをリセット",
    empty: "ワークスペースを作成するか、エージェントを登録してください。",
    open: "詳細を開く",
    channel: "ワークスペースを開く",
    close: "詳細を閉じる",
    focus: "周辺の関係に絞る",
    unfocus: "グラフ全体を表示",
    zoomIn: "拡大",
    zoomOut: "縮小",
    fit: "全体を表示",
    center: "選択ノードを中央に",
    minimap: "グラフのミニマップ — クリックして移動",
    fullscreen: "全画面表示を切り替え",
    select: "ノードの詳細",
    snapshot: "認可済みスナップショット · 設定上の関係と記録された活動",
    omitted: "表示範囲外",
    local: "ローカルエージェント",
    tools: "ツール",
    artifacts: "成果物",
    external: "外部エージェント",
    unknown: "状態の情報なし",
    configured: "設定済み",
    discovered: "検出済み",
    localNode: "ローカル",
    running: "実行中タスク",
    blocked: "ブロック中",
    completed: "完了タスク",
    pending: "未着手タスク",
    timeline: "実行タイムライン",
    noTimeline: "この期間に記録されたイベントはありません",
    more: "グラフのその他の操作",
    export: "グラフをPNGで保存",
    fullDetails: "エージェントの関係",
    live: "5秒ごとに最新の状態を取得",
    counts: "ノード",
    links: "接続",
    windowHelp:
      "実行記録とイベントの期間を絞ります。実行中の処理と現在のタスク・設定は表示を維持します。",
    noSelection: "ノードを選択すると関係を確認できます。",
  },
};
export type MeshCopy = (typeof meshCopy)["en-US"];
