export const workspaceCopy = {
  "ja-JP": {
    workspace: "ワークスペース",
    subtitle: "Human × Agent collaboration",
    goalChannels: "ゴール別チャンネル",
    conversations: "エージェントとの会話",
    threads: "このチャンネルのスレッド",
    noThreads: "表示中の履歴にスレッドはありません。",
    search: "チャンネル名・ゴールを検索",
    noMatches: "一致するチャンネルはありません。",
    addAgent: "チームにエージェントを追加",
    addAgentHelp: "得意な仕事から探して、一緒に働く仲間を選びましょう。",
    marketplace: "Marketplace を開く",
    account: "アカウント設定",
    notifications: "確認待ちの通知",
    noNotifications: "確認待ちのリクエストはありません。",
    status: "チャンネルの状況",
    sharedGoal: "SHARED GOAL",
    currentTasks: "現在のタスク",
    showAll: "すべて表示",
    participants: "参加エージェント",
    manage: "タスクを割り当て",
    connections: "エージェントの連携",
    snapshot: "現在取得できる実行と依存関係",
    nodes: "ノード",
    local: "local",
    peer: "peer node",
    preparing: "準備中",
    active: "進行中",
    completed: "実行完了",
    paused: "一時停止中",
    pause: "このチャンネルの実行を一時停止",
    resume: "このチャンネルの実行を再開",
    partialFailure:
      "一部の実行を変更できませんでした。状態を確認して再試行してください。",
    messages: "メッセージ",
    events: "イベント",
    task: "タスク",
    scope: "このチャンネルの参加者に共有",
    attach: "ファイルを添付",
    attachmentLimit:
      "1ファイル 1 MiB 以下・最大8件。メッセージ本文も入力してください。",
    invalidAttachment:
      "添付できるのは空でない1 MiB以下のファイル（最大8件）です。",
    removeAttachment: "添付を削除",
    uploading: "アップロード中…",
    attachmentError: "添付できませんでした。ファイルは保持しています。",
    bold: "太字",
    italic: "斜体",
    code: "コード",
    mention: "エージェント名を挿入",
    mentionHelp: "名前の挿入は通知・実行を開始しません。",
    enterHint: "Enter で送信 · Shift + Enter で改行",
    approve: "承認する",
    reject: "却下",
    answer: "回答・変更を依頼",
    approval: "人間の確認が必要",
    details: "状況を表示",
    close: "閉じる",
    taskCounts: "件のタスク完了",
    waiting: "確認待ち",
    noParticipants: "まだ実行エージェントはいません。",
    settings: "ワークスペース設定",
    history: "会話・実行履歴",
    access: "現在のアクセス権限で表示",
    newConversation: "エージェントとの会話を開始",
  },
  "en-US": {
    workspace: "Workspace",
    subtitle: "Human × Agent collaboration",
    goalChannels: "Goal channels",
    conversations: "Agent conversations",
    threads: "Threads in this channel",
    noThreads: "No threads in the loaded history.",
    search: "Search channel names and goals",
    noMatches: "No matching channels.",
    addAgent: "Add an agent to your team",
    addAgentHelp: "Find the right skills and choose who you work with.",
    marketplace: "Explore Marketplace",
    account: "Account settings",
    notifications: "Requests awaiting your input",
    noNotifications: "No requests awaiting your input.",
    status: "Channel status",
    sharedGoal: "SHARED GOAL",
    currentTasks: "Current tasks",
    showAll: "Show all",
    participants: "Participating agents",
    manage: "Assign a task",
    connections: "Agent collaboration",
    snapshot: "Currently available runs and dependencies",
    nodes: "nodes",
    local: "local",
    peer: "peer node",
    preparing: "Preparing",
    active: "In progress",
    completed: "Runs completed",
    paused: "Paused",
    pause: "Pause runs in this channel",
    resume: "Resume runs in this channel",
    partialFailure:
      "Some runs could not be updated. Check their state and retry.",
    messages: "Messages",
    events: "Events",
    task: "Tasks",
    scope: "Shared with this channel's participants",
    attach: "Attach files",
    attachmentLimit:
      "Up to 8 files, 1 MiB each. Include a message with your files.",
    invalidAttachment: "Choose up to 8 non-empty files of 1 MiB or less.",
    removeAttachment: "Remove attachment",
    uploading: "Uploading…",
    attachmentError: "Upload failed. Your files have been kept.",
    bold: "Bold",
    italic: "Italic",
    code: "Code",
    mention: "Insert an agent name",
    mentionHelp: "Inserting a name does not notify or start the agent.",
    enterHint: "Enter to send · Shift + Enter for a new line",
    approve: "Approve",
    reject: "Reject",
    answer: "Respond or request changes",
    approval: "Human review required",
    details: "Show channel status",
    close: "Close",
    taskCounts: "tasks completed",
    waiting: "Awaiting input",
    noParticipants: "No execution agents yet.",
    settings: "Workspace settings",
    history: "Conversation and execution history",
    access: "Visible under your current access",
    newConversation: "Start an agent conversation",
  },
} as const;
