//! Persistent atomic_history records.

use crate::Result;
use crate::apps::federation::transactions::services::states::AtomicHistoryRole;
use chrono::{DateTime, Utc};
use reinhardt::db::backends::TransactionExecutor;
use reinhardt::db::orm::execution::convert_values;
use reinhardt::model;
use reinhardt::query::{Alias, PostgresQueryBuilder, Query, QueryStatementBuilder};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[model(app_label = "federation", table_name = "atomic_history")]
#[derive(Serialize, Deserialize)]
pub struct AtomicHistory {
	#[field(primary_key = true)]
	pub sequence: i64,
	#[field]
	pub transaction_id: uuid::Uuid,
	#[field(field_type = "text", max_length = 64)]
	pub role: AtomicHistoryRole,
	#[field(field_type = "text")]
	pub phase: String,
	#[field(field_type = "text")]
	pub detail: String,
	#[field(auto_now_add = true)]
	pub created_at: DateTime<Utc>,
}

impl AtomicHistory {
	pub(crate) async fn append<E: TransactionExecutor + ?Sized>(
		tx: &mut E,
		id: Uuid,
		role: &str,
		phase: &str,
		detail: &str,
	) -> Result<()> {
		// Identity sequences are generated by PostgreSQL; omit them from the insert.
		let (sql, values) = Query::insert()
			.into_table(Alias::new("atomic_history"))
			.columns([
				Alias::new("transaction_id"),
				Alias::new("role"),
				Alias::new("phase"),
				Alias::new("detail"),
			])
			.values_panic([
				IntoValue::into_value(id),
				IntoValue::into_value(role),
				IntoValue::into_value(phase),
				IntoValue::into_value(detail),
			])
			.build(PostgresQueryBuilder);
		tx.execute(&sql, convert_values(values)).await?;
		Ok(())
	}
}

use reinhardt::query::IntoValue;
